# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Adicionar_nodo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_Adicionar_nodo(object):
	def setupUi(self, Dialog):
		if not Dialog.objectName():
			Dialog.setObjectName("Dialog")
		Dialog.resize(270, 189)
		Dialog.setStyleSheet(u"QDialog#Dialog{\n"
"background:tranparent;\n"
"}")
		Dialog.setWindowFlags(QtCore.Qt.Popup | QtCore.Qt.FramelessWindowHint | QtCore.Qt.NoDropShadowWindowHint)
		Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
		self.frame = QtWidgets.QFrame(Dialog)
		self.frame.setGeometry(QtCore.QRect(0, 0, 270, 189))
		self.frame.setStyleSheet("QFrame#frame{\n"
"    border: 2px solid rgb(39, 142, 39);\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    border: 1px solid rgb(208, 208, 191);\n"
"    border-radius: 3px;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"\n"
"QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    text-align: right;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame.setObjectName("frame")
		self.pushButton = QtWidgets.QPushButton(self.frame)
		self.pushButton.setGeometry(QtCore.QRect(180, 160, 75, 23))
		self.pushButton.setObjectName("pushButton")
		self.widget = QtWidgets.QWidget(self.frame)
		self.widget.setGeometry(QtCore.QRect(15, 12, 241, 136))
		self.widget.setObjectName("widget")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.label_2 = QtWidgets.QLabel(self.widget)
		self.label_2.setObjectName("label_2")
		self.horizontalLayout.addWidget(self.label_2)
		spacerItem = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem)
		self.lineEdit = QtWidgets.QLineEdit(self.widget)
		self.lineEdit.setObjectName("lineEdit")
		self.horizontalLayout.addWidget(self.lineEdit)
		self.verticalLayout.addLayout(self.horizontalLayout)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.label_3 = QtWidgets.QLabel(self.widget)
		self.label_3.setObjectName("label_3")
		self.horizontalLayout_2.addWidget(self.label_3)
		spacerItem1 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem1)
		self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
		self.lineEdit_2.setObjectName("lineEdit_2")
		self.horizontalLayout_2.addWidget(self.lineEdit_2)
		self.verticalLayout.addLayout(self.horizontalLayout_2)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.label_4 = QtWidgets.QLabel(self.widget)
		self.label_4.setObjectName("label_4")
		self.horizontalLayout_3.addWidget(self.label_4)
		spacerItem2 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_3.addItem(spacerItem2)
		self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
		self.lineEdit_3.setObjectName("lineEdit_3")
		self.horizontalLayout_3.addWidget(self.lineEdit_3)
		self.verticalLayout.addLayout(self.horizontalLayout_3)
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.label_5 = QtWidgets.QLabel(self.widget)
		self.label_5.setObjectName("label_5")
		self.horizontalLayout_4.addWidget(self.label_5)
		spacerItem3 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem3)
		self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
		self.lineEdit_4.setObjectName("lineEdit_4")
		self.horizontalLayout_4.addWidget(self.lineEdit_4)
		self.verticalLayout.addLayout(self.horizontalLayout_4)
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.label = QtWidgets.QLabel(self.widget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(61)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
		self.label.setSizePolicy(sizePolicy)
		self.label.setObjectName("label")
		self.horizontalLayout_5.addWidget(self.label)
		spacerItem4 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_5.addItem(spacerItem4)
		self.comboBox = QtWidgets.QComboBox(self.widget)
		self.comboBox.setObjectName("comboBox")
		self.comboBox.addItem("")
		self.comboBox.addItem("")
		self.horizontalLayout_5.addWidget(self.comboBox)
		self.verticalLayout.addLayout(self.horizontalLayout_5)

		self.retranslateUi(Dialog)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
		self.pushButton.setText(_translate("Dialog", "Adicionar"))
		self.label_2.setText(_translate("Dialog", "Nombre del Nodo"))
		self.label_3.setText(_translate("Dialog", "Título EA"))
		self.label_4.setText(_translate("Dialog", "IP"))
		self.label_5.setText(_translate("Dialog", "Puerto"))
		self.label.setText(_translate("Dialog", "Tipo"))
		self.comboBox.setItemText(0, _translate("Dialog", "Estación"))
		self.comboBox.setItemText(1, _translate("Dialog", "Servidor"))

