# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Bandeja_de_casos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Bandeja_de_casos(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.resize(1260, 609)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Dialog.setWindowIcon(icon)
		self.frame = QtWidgets.QFrame(Dialog)
		self.frame.setGeometry(QtCore.QRect(0, 0, 1261, 611))
		self.frame.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(0, 85, 255);\n"
"}")
		self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame.setObjectName("frame")
		self.tabWidget = QtWidgets.QTabWidget(self.frame)
		self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1261, 601))
		self.tabWidget.setStyleSheet("QTabWidget#tabWidget::pane {\n"
"    border-top: 1px solid #C2C7CB;\n"
"    top: -0.2em;\n"
"}\n"
"\n"
"QTabWidget#tabWidget::tab-bar{\n"
"    left: 5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: rgb(201, 201, 201);\n"
"    border: 1px solid rgb(94, 94, 94);\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    min-width: 0.1ex;\n"
"    padding: 5px;\n"
"    margin-left: 5px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: rgb(94, 94, 94);\n"
"    border-bottom-color:  rgb(201, 201, 201); /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover{\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:1, y1:0.539773, x2:0, y2:0.534, stop:0 rgba(201, 201, 201, 255), stop:0.495 rgba(201, 201, 201, 255), stop:0.505 rgba(94, 94, 94, 255), stop:1 rgba(94, 94, 94, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.489, y1:1, x2:0.5, y2:0, stop:0 rgba(201, 201, 201, 255), stop:0.495 rgba(201, 201, 201, 255), stop:0.505 rgba(94, 94, 94, 255), stop:1 rgba(94, 94, 94, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534, x2:1, y2:0.539773, stop:0 rgba(201, 201, 201, 255), stop:0.495 rgba(201, 201, 201, 255), stop:0.505 rgba(94, 94, 94, 255), stop:1 rgba(94, 94, 94, 255));\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-color:  rgb(201, 201, 201);\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabWidget#tabWidget::tab{\n"
"    background-color: rgb(255, 0, 127);\n"
"}\n"
"\n"
"QFrame#frame_3, QFrame#frame_4{\n"
"    background-color: rgb(201, 201, 201);\n"
"}")
		self.tabWidget.setTabBarAutoHide(False)
		self.tabWidget.setObjectName("tabWidget")
		self.tab = QtWidgets.QWidget()
		self.tab.setObjectName("tab")
		self.frame_3 = QtWidgets.QFrame(self.tab)
		self.frame_3.setGeometry(QtCore.QRect(-20, -10, 1281, 591))
		self.frame_3.setStyleSheet("background-color: rgb(201, 201, 201);")
		self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_3.setObjectName("frame_3")
		self.frame_9 = QtWidgets.QFrame(self.frame_3)
		self.frame_9.setGeometry(QtCore.QRect(20, 10, 1261, 85))
		self.frame_9.setStyleSheet("QFrame#frame_9{\n"
"    background-color: rgb(255, 0, 255);\n"
"}")
		self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_9.setObjectName("frame_9")
		self.frame_12 = QtWidgets.QFrame(self.frame_9)
		self.frame_12.setGeometry(QtCore.QRect(0, 0, 161, 85))
		self.frame_12.setStyleSheet("QFrame#frame_12{\n"
"    background-color: qlineargradient(spread:pad, x1:0.506, y1:1, x2:0.499955, y2:0.636, stop:0 rgba(165, 165, 165, 255), stop:1 rgba(201, 201, 201, 255));\n"
"    border-bottom: 1px solid rgb(112, 112, 112);\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.506, y2:0, stop:0 rgba(112, 112, 112, 255), stop:1 rgba(184, 184, 184, 255))\n"
"}")
		self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_12.setObjectName("frame_12")
		self.label_8 = QtWidgets.QLabel(self.frame_12)
		self.label_8.setGeometry(QtCore.QRect(50, 68, 61, 16))
		self.label_8.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: rgb(36, 36, 36)\n"
"}")
		self.label_8.setObjectName("label_8")
		self.frame_18 = QtWidgets.QFrame(self.frame_12)
		self.frame_18.setGeometry(QtCore.QRect(2, 3, 51, 66))
		self.frame_18.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_18.setProperty("checkable", False)
		self.frame_18.setObjectName("frame_18")
		self.toolButton_4 = QtWidgets.QToolButton(self.frame_18)
		self.toolButton_4.setGeometry(QtCore.QRect(0, 0, 51, 66))
		self.toolButton_4.setStyleSheet("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/openFile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton_4.setIcon(icon)
		self.toolButton_4.setIconSize(QtCore.QSize(39, 39))
		self.toolButton_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolButton_4.setObjectName("toolButton_4")
		self.frame_19 = QtWidgets.QFrame(self.frame_12)
		self.frame_19.setGeometry(QtCore.QRect(54, 2, 51, 66))
		self.frame_19.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_19.setObjectName("frame_19")
		self.toolButton_5 = QtWidgets.QToolButton(self.frame_19)
		self.toolButton_5.setGeometry(QtCore.QRect(0, 0, 51, 66))
		font = QtGui.QFont()
		font.setPointSize(8)
		self.toolButton_5.setFont(font)
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/openBlue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton_5.setIcon(icon1)
		self.toolButton_5.setIconSize(QtCore.QSize(43, 51))
		self.toolButton_5.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolButton_5.setAutoRaise(False)
		self.toolButton_5.setArrowType(QtCore.Qt.NoArrow)
		self.toolButton_5.setObjectName("toolButton_5")
		self.frame_20 = QtWidgets.QFrame(self.frame_12)
		self.frame_20.setGeometry(QtCore.QRect(106, 3, 51, 66))
		self.frame_20.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_20.setObjectName("frame_20")
		self.toolButton = QtWidgets.QToolButton(self.frame_20)
		self.toolButton.setGeometry(QtCore.QRect(0, 0, 51, 66))
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton.setIcon(icon2)
		self.toolButton.setIconSize(QtCore.QSize(42, 49))
		self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolButton.setObjectName("toolButton")
		self.frame_13 = QtWidgets.QFrame(self.frame_9)
		self.frame_13.setGeometry(QtCore.QRect(160, 0, 261, 85))
		self.frame_13.setStyleSheet("QFrame#frame_13{\n"
"    background-color: qlineargradient(spread:pad, x1:0.506, y1:1, x2:0.499955, y2:0.636, stop:0 rgba(165, 165, 165, 255), stop:1 rgba(201, 201, 201, 255));\n"
"    border-bottom: 1px solid rgb(112, 112, 112);\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.506, y2:0, stop:0 rgba(112, 112, 112, 255), stop:1 rgba(184, 184, 184, 255))\n"
"}")
		self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_13.setObjectName("frame_13")
		self.label_9 = QtWidgets.QLabel(self.frame_13)
		self.label_9.setGeometry(QtCore.QRect(115, 68, 31, 16))
		self.label_9.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: rgb(36, 36, 36)\n"
"}")
		self.label_9.setObjectName("label_9")
		self.frame_21 = QtWidgets.QFrame(self.frame_13)
		self.frame_21.setGeometry(QtCore.QRect(4, 3, 67, 66))
		self.frame_21.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_21.setObjectName("frame_21")
		self.toolButton_2 = QtWidgets.QToolButton(self.frame_21)
		self.toolButton_2.setGeometry(QtCore.QRect(0, 0, 67, 66))
		self.toolButton_2.setAcceptDrops(False)
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/sendViewer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton_2.setIcon(icon3)
		self.toolButton_2.setIconSize(QtCore.QSize(37, 36))
		self.toolButton_2.setCheckable(False)
		self.toolButton_2.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
		self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolButton_2.setAutoRaise(False)
		self.toolButton_2.setArrowType(QtCore.Qt.NoArrow)
		self.toolButton_2.setObjectName("toolButton_2")
		self.frame_22 = QtWidgets.QFrame(self.frame_13)
		self.frame_22.setGeometry(QtCore.QRect(72, 3, 67, 66))
		self.frame_22.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    border:none;\n"
"padding: 20px;\n"
"}\n"
"\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_22.setObjectName("frame_22")
		self.frame_29 = QtWidgets.QFrame(self.frame_22)
		self.frame_29.setGeometry(QtCore.QRect(0, 0, 68, 38))
		self.frame_29.setStyleSheet("")
		self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_29.setObjectName("frame_29")
		self.label_13 = QtWidgets.QLabel(self.frame_29)
		self.label_13.setGeometry(QtCore.QRect(16, 5, 41, 31))
		self.label_13.setStyleSheet("")
		self.label_13.setText("")
		self.label_13.setPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/sendNewViewer.png"))
		self.label_13.setObjectName("label_13")
		self.toolButton_3 = QtWidgets.QToolButton(self.frame_22)
		self.toolButton_3.setGeometry(QtCore.QRect(0, 36, 67, 29))
		self.toolButton_3.setIconSize(QtCore.QSize(3, 4))
		self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
		self.toolButton_3.setArrowType(QtCore.Qt.DownArrow)
		self.toolButton_3.setObjectName("toolButton_3")
		self.frame_23 = QtWidgets.QFrame(self.frame_13)
		self.frame_23.setGeometry(QtCore.QRect(140, 3, 59, 66))
		self.frame_23.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_23.setObjectName("frame_23")
		self.toolButton_6 = QtWidgets.QToolButton(self.frame_23)
		self.toolButton_6.setGeometry(QtCore.QRect(0, 0, 59, 67))
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/sendServer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton_6.setIcon(icon4)
		self.toolButton_6.setIconSize(QtCore.QSize(35, 39))
		self.toolButton_6.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolButton_6.setObjectName("toolButton_6")
		self.frame_24 = QtWidgets.QFrame(self.frame_13)
		self.frame_24.setGeometry(QtCore.QRect(200, 3, 57, 66))
		self.frame_24.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_24.setObjectName("frame_24")
		self.toolButton_7 = QtWidgets.QToolButton(self.frame_24)
		self.toolButton_7.setGeometry(QtCore.QRect(0, 0, 57, 66))
		icon5 = QtGui.QIcon()
		icon5.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/sendEmail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton_7.setIcon(icon5)
		self.toolButton_7.setIconSize(QtCore.QSize(42, 41))
		self.toolButton_7.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolButton_7.setObjectName("toolButton_7")
		self.frame_14 = QtWidgets.QFrame(self.frame_9)
		self.frame_14.setGeometry(QtCore.QRect(420, 0, 131, 85))
		self.frame_14.setStyleSheet("QFrame#frame_14{\n"
"    background-color: qlineargradient(spread:pad, x1:0.506, y1:1, x2:0.499955, y2:0.636, stop:0 rgba(165, 165, 165, 255), stop:1 rgba(201, 201, 201, 255));\n"
"    border-bottom: 1px solid rgb(112, 112, 112);\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.506, y2:0, stop:0 rgba(112, 112, 112, 255), stop:1 rgba(184, 184, 184, 255))\n"
"}")
		self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_14.setObjectName("frame_14")
		self.label_10 = QtWidgets.QLabel(self.frame_14)
		self.label_10.setGeometry(QtCore.QRect(44, 68, 41, 16))
		self.label_10.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: rgb(36, 36, 36)\n"
"}")
		self.label_10.setObjectName("label_10")
		self.frame_25 = QtWidgets.QFrame(self.frame_14)
		self.frame_25.setGeometry(QtCore.QRect(4, 3, 53, 66))
		self.frame_25.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    border:none;\n"
"padding: 20px;\n"
"}\n"
"\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_25.setObjectName("frame_25")
		self.frame_30 = QtWidgets.QFrame(self.frame_25)
		self.frame_30.setGeometry(QtCore.QRect(0, 0, 68, 38))
		self.frame_30.setStyleSheet("")
		self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_30.setObjectName("frame_30")
		self.label_14 = QtWidgets.QLabel(self.frame_30)
		self.label_14.setGeometry(QtCore.QRect(12, 4, 41, 33))
		self.label_14.setStyleSheet("")
		self.label_14.setText("")
		self.label_14.setPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/burn.png"))
		self.label_14.setObjectName("label_14")
		self.toolButton_8 = QtWidgets.QToolButton(self.frame_25)
		self.toolButton_8.setGeometry(QtCore.QRect(0, 36, 53, 29))
		self.toolButton_8.setIconSize(QtCore.QSize(3, 4))
		self.toolButton_8.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
		self.toolButton_8.setArrowType(QtCore.Qt.DownArrow)
		self.toolButton_8.setObjectName("toolButton_8")
		self.frame_26 = QtWidgets.QFrame(self.frame_14)
		self.frame_26.setGeometry(QtCore.QRect(59, 3, 67, 66))
		self.frame_26.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QLabel{\n"
"    border:none;\n"
"}\n"
"\n"
"QLabel:hover{\n"
"    border:none;\n"
"padding: 20px;\n"
"}\n"
"\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_26.setObjectName("frame_26")
		self.frame_31 = QtWidgets.QFrame(self.frame_26)
		self.frame_31.setGeometry(QtCore.QRect(0, 0, 68, 38))
		self.frame_31.setStyleSheet("")
		self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_31.setObjectName("frame_31")
		self.label_15 = QtWidgets.QLabel(self.frame_31)
		self.label_15.setGeometry(QtCore.QRect(16, 5, 41, 31))
		self.label_15.setStyleSheet("")
		self.label_15.setText("")
		self.label_15.setPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/exportDevice.png"))
		self.label_15.setObjectName("label_15")
		self.toolButton_9 = QtWidgets.QToolButton(self.frame_26)
		self.toolButton_9.setGeometry(QtCore.QRect(0, 36, 67, 29))
		self.toolButton_9.setIconSize(QtCore.QSize(3, 4))
		self.toolButton_9.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
		self.toolButton_9.setArrowType(QtCore.Qt.DownArrow)
		self.toolButton_9.setObjectName("toolButton_9")
		self.frame_15 = QtWidgets.QFrame(self.frame_9)
		self.frame_15.setGeometry(QtCore.QRect(550, 0, 91, 85))
		self.frame_15.setStyleSheet("QFrame#frame_15{\n"
"    background-color: qlineargradient(spread:pad, x1:0.506, y1:1, x2:0.499955, y2:0.636, stop:0 rgba(165, 165, 165, 255), stop:1 rgba(201, 201, 201, 255));\n"
"    border-bottom: 1px solid rgb(112, 112, 112);\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.506, y2:0, stop:0 rgba(112, 112, 112, 255), stop:1 rgba(184, 184, 184, 255))\n"
"}")
		self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_15.setObjectName("frame_15")
		self.label_11 = QtWidgets.QLabel(self.frame_15)
		self.label_11.setGeometry(QtCore.QRect(21, 68, 51, 16))
		self.label_11.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: rgb(36, 36, 36)\n"
"}")
		self.label_11.setObjectName("label_11")
		self.frame_27 = QtWidgets.QFrame(self.frame_15)
		self.frame_27.setGeometry(QtCore.QRect(4, 3, 83, 66))
		self.frame_27.setStyleSheet("QFrame{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolButton{\n"
"    background-color: transparent;\n"
"    }\n"
"\n"
"QToolButton:hover{\n"
"    background-color: qlineargradient(spread:reflect, x1:0.455273, y1:1, x2:0.460273, y2:0, stop:0 rgba(253, 247, 225, 255), stop:0.301136 rgba(252, 228, 137, 255), stop:0.829545 rgba(253, 235, 168, 255), stop:1 rgba(253, 238, 177, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.465909, y1:0, x2:0.465909, y2:1, stop:0 rgba(241, 202, 88, 255), stop:1 rgba(253, 249, 232, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.994318, y1:0.568, x2:0, y2:0.568, stop:0 rgba(241, 204, 84, 255), stop:1 rgba(253, 246, 221, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.471, y1:1, x2:0.494, y2:0, stop:0 rgba(244, 213, 73, 255), stop:1 rgba(253, 253, 235, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.642, x2:1, y2:0.659, stop:0 rgba(242, 205, 83, 255), stop:1 rgba(253, 246, 223, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"    background-color: qlineargradient(spread:pad, x1:0.483, y1:1, x2:0.477, y2:0.426, stop:0 rgba(254, 226, 135, 255), stop:1 rgba(250, 214, 121, 255));\n"
"    border-top: 2px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.517, y2:1, stop:0 rgba(194, 118, 43, 255), stop:1 rgba(246, 200, 103, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:1, y1:0.557, x2:0, y2:0.563, stop:0 rgba(194, 128, 50, 255), stop:1 rgba(248, 208, 113, 255));\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0.449, y1:1, x2:0.449, y2:0, stop:0 rgba(194, 158, 71, 255), stop:1 rgba(250, 215, 122, 255));\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0, y1:0.545455, x2:1, y2:0.54, stop:0 rgba(194, 132, 53, 255), stop:1 rgba(248, 209, 114, 255));\n"
"    border-radius: 1.5ex;\n"
"}\n"
"\n"
"")
		self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_27.setObjectName("frame_27")
		self.toolButton_10 = QtWidgets.QToolButton(self.frame_27)
		self.toolButton_10.setGeometry(QtCore.QRect(0, 0, 83, 66))
		icon6 = QtGui.QIcon()
		icon6.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/configuration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolButton_10.setIcon(icon6)
		self.toolButton_10.setIconSize(QtCore.QSize(37, 48))
		self.toolButton_10.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolButton_10.setObjectName("toolButton_10")
		self.frame_16 = QtWidgets.QFrame(self.frame_9)
		self.frame_16.setGeometry(QtCore.QRect(640, 0, 361, 85))
		self.frame_16.setStyleSheet("QFrame#frame_16{\n"
"    background-color: qlineargradient(spread:pad, x1:0.506, y1:1, x2:0.499955, y2:0.636, stop:0 rgba(165, 165, 165, 255), stop:1 rgba(201, 201, 201, 255));\n"
"    border-bottom: 1px solid rgb(112, 112, 112);\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.506, y2:0, stop:0 rgba(112, 112, 112, 255), stop:1 rgba(184, 184, 184, 255))\n"
"}")
		self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_16.setObjectName("frame_16")
		self.label_12 = QtWidgets.QLabel(self.frame_16)
		self.label_12.setGeometry(QtCore.QRect(132, 68, 81, 16))
		self.label_12.setStyleSheet("QLabel{\n"
"    background-color: transparent;\n"
"    color: rgb(36, 36, 36)\n"
"}")
		self.label_12.setObjectName("label_12")
		self.frame_28 = QtWidgets.QFrame(self.frame_16)
		self.frame_28.setGeometry(QtCore.QRect(4, 3, 352, 66))
		self.frame_28.setStyleSheet("background-color: transparent;")
		self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_28.setObjectName("frame_28")
		self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_28)
		self.tabWidget_2.setGeometry(QtCore.QRect(3, 0, 347, 63))
		self.tabWidget_2.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border: 1px solid rgb(211, 211, 211);\n"
"    border-radius: 5px;\n"
"    position: absolute;\n"
"    top: -0.6em;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    padding: 0.1ex;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border-radius: 0px;\n"
"    margin-left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(236, 240, 248);\n"
"    border: 1px solid rgb(51, 51, 51);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(134, 134, 134);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.517, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(134, 134, 134, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.517, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(134, 134, 134, 255));\n"
"}")
		self.tabWidget_2.setObjectName("tabWidget_2")
		self.tab_4 = QtWidgets.QWidget()
		self.tab_4.setObjectName("tab_4")
		self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_4)
		self.lineEdit_4.setGeometry(QtCore.QRect(50, 18, 251, 24))
		self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    padding: 5px;\n"
"    border: 1px solid rgb(208, 208, 191);\n"
"    border-radius: 6px;\n"
"    background-color: rgb(246, 246, 246);\n"
"}")
		self.lineEdit_4.setObjectName("lineEdit_4")
		self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
		self.pushButton_4.setGeometry(QtCore.QRect(272, 20, 23, 20))
		self.pushButton_4.setText("")
		icon7 = QtGui.QIcon()
		icon7.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/Browse12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.pushButton_4.setIcon(icon7)
		self.pushButton_4.setIconSize(QtCore.QSize(23, 22))
		self.pushButton_4.setObjectName("pushButton_4")
		self.tabWidget_2.addTab(self.tab_4, "")
		self.tab_5 = QtWidgets.QWidget()
		self.tab_5.setObjectName("tab_5")
		self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
		self.pushButton_5.setGeometry(QtCore.QRect(272, 20, 23, 20))
		self.pushButton_5.setText("")
		self.pushButton_5.setIcon(icon7)
		self.pushButton_5.setIconSize(QtCore.QSize(23, 22))
		self.pushButton_5.setObjectName("pushButton_5")
		self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
		self.lineEdit_5.setGeometry(QtCore.QRect(50, 18, 251, 24))
		self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"    padding: 5px;\n"
"    border: 1px solid rgb(208, 208, 191);\n"
"    border-radius: 6px;\n"
"    background-color: rgb(246, 246, 246);\n"
"}")
		self.lineEdit_5.setObjectName("lineEdit_5")
		self.lineEdit_5.raise_()
		self.pushButton_5.raise_()
		self.tabWidget_2.addTab(self.tab_5, "")
		self.tab_6 = QtWidgets.QWidget()
		self.tab_6.setObjectName("tab_6")
		self.frame_32 = QtWidgets.QFrame(self.tab_6)
		self.frame_32.setGeometry(QtCore.QRect(50, 18, 251, 24))
		self.frame_32.setStyleSheet("QFrame{\n"
"    padding: 5px;\n"
"    border: 1px solid rgb(208, 208, 191);\n"
"    border-radius: 6px;\n"
"    background-color: rgb(246, 246, 246);\n"
"}")
		self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_32.setObjectName("frame_32")
		self.pushButton_6 = QtWidgets.QPushButton(self.frame_32)
		self.pushButton_6.setGeometry(QtCore.QRect(222, 2, 23, 20))
		self.pushButton_6.setText("")
		self.pushButton_6.setIcon(icon7)
		self.pushButton_6.setIconSize(QtCore.QSize(23, 22))
		self.pushButton_6.setObjectName("pushButton_6")
		self.radioButton_10 = QtWidgets.QRadioButton(self.frame_32)
		self.radioButton_10.setGeometry(QtCore.QRect(9, 3, 51, 17))
		self.radioButton_10.setObjectName("radioButton_10")
		self.radioButton_11 = QtWidgets.QRadioButton(self.frame_32)
		self.radioButton_11.setGeometry(QtCore.QRect(74, 3, 71, 17))
		self.radioButton_11.setObjectName("radioButton_11")
		self.radioButton_12 = QtWidgets.QRadioButton(self.frame_32)
		self.radioButton_12.setGeometry(QtCore.QRect(151, 3, 71, 17))
		self.radioButton_12.setObjectName("radioButton_12")
		self.tabWidget_2.addTab(self.tab_6, "")
		self.frame_17 = QtWidgets.QFrame(self.frame_9)
		self.frame_17.setGeometry(QtCore.QRect(1000, 0, 261, 85))
		self.frame_17.setStyleSheet("QFrame#frame_17{\n"
"    background-color: qlineargradient(spread:pad, x1:0.506, y1:1, x2:0.499955, y2:0.636, stop:0 rgba(165, 165, 165, 255), stop:1 rgba(201, 201, 201, 255));\n"
"    border-bottom: 1px solid rgb(112, 112, 112);\n"
"}")
		self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_17.setObjectName("frame_17")
		self.frame_17.raise_()
		self.frame_16.raise_()
		self.frame_15.raise_()
		self.frame_14.raise_()
		self.frame_13.raise_()
		self.frame_12.raise_()
		self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_3)
		self.tableWidget_3.setGeometry(QtCore.QRect(10, 101, 1271, 271))
		font = QtGui.QFont()
		font.setBold(False)
		font.setWeight(50)
		self.tableWidget_3.setFont(font)
		self.tableWidget_3.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494, y2:0, stop:0 rgba(117, 160, 229, 255), stop:1 rgba(233, 238, 248, 255));\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    border:none;\n"
"    border-left: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"")
		self.tableWidget_3.setObjectName("tableWidget_3")
		self.tableWidget_3.setColumnCount(8)
		self.tableWidget_3.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_3.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_3.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_3.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_3.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_3.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_3.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_3.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_3.setHorizontalHeaderItem(7, item)
		self.tableWidget_3.horizontalHeader().setCascadingSectionResizes(False)
		self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
		self.frame_10 = QtWidgets.QFrame(self.frame_3)
		self.frame_10.setGeometry(QtCore.QRect(20, 380, 601, 211))
		self.frame_10.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(162, 162, 162);\n"
"}")
		self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_10.setObjectName("frame_10")
		self.groupBox_5 = QtWidgets.QGroupBox(self.frame_10)
		self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 581, 191))
		self.groupBox_5.setStyleSheet("QGroupBox {\n"
"    border-left: 3px solid qlineargradient(spread:reflect, x1:0, y1:0.5, x2:1, y2:0.494, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-top: 3px solid qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0.494, y2:1, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-right: 3px solid qlineargradient(spread:reflect, x1:0, y1:0.5, x2:1, y2:0.494, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-bottom: 3px solid qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0.494, y2:1, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-radius: 5px;\n"
"    \n"
"    background-color: rgb(162, 162, 162);\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px;\n"
"      color:rgb(0, 70, 213)\n"
"}")
		self.groupBox_5.setObjectName("groupBox_5")
		self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_5)
		self.tableWidget_4.setGeometry(QtCore.QRect(10, 20, 561, 161))
		self.tableWidget_4.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(197, 197, 197);\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494, y2:0, stop:0 rgba(117, 160, 229, 255), stop:1 rgba(233, 238, 248, 255));\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    border:none;\n"
"    border-left: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"")
		self.tableWidget_4.setObjectName("tableWidget_4")
		self.tableWidget_4.setColumnCount(6)
		self.tableWidget_4.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_4.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_4.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_4.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_4.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_4.setHorizontalHeaderItem(5, item)
		self.frame_11 = QtWidgets.QFrame(self.frame_3)
		self.frame_11.setGeometry(QtCore.QRect(630, 380, 651, 211))
		self.frame_11.setStyleSheet("QFrame#frame_11{\n"
"    background-color: rgb(162, 162, 162);\n"
"}")
		self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_11.setObjectName("frame_11")
		self.groupBox_6 = QtWidgets.QGroupBox(self.frame_11)
		self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 631, 191))
		self.groupBox_6.setStyleSheet("QGroupBox {\n"
"    border-left: 3px solid qlineargradient(spread:reflect, x1:0, y1:0.5, x2:1, y2:0.494, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-top: 3px solid qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0.494, y2:1, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-right: 3px solid qlineargradient(spread:reflect, x1:0, y1:0.5, x2:1, y2:0.494, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-bottom: 3px solid qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0.494, y2:1, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-radius: 5px;\n"
"    \n"
"    background-color: rgb(162, 162, 162);\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px;\n"
"      color:rgb(0, 70, 213)\n"
"}")
		self.groupBox_6.setObjectName("groupBox_6")
		self.tableWidget_5 = QtWidgets.QTableWidget(self.groupBox_6)
		self.tableWidget_5.setGeometry(QtCore.QRect(10, 20, 611, 161))
		self.tableWidget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.tableWidget_5.setObjectName("tableWidget_5")
		self.tableWidget_5.setColumnCount(0)
		self.tableWidget_5.setRowCount(0)
		self.tabWidget.addTab(self.tab, "")
		self.tab_2 = QtWidgets.QWidget()
		self.tab_2.setObjectName("tab_2")
		self.frame_4 = QtWidgets.QFrame(self.tab_2)
		self.frame_4.setGeometry(QtCore.QRect(-20, -10, 1281, 591))
		self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_4.setObjectName("frame_4")
		self.frame_5 = QtWidgets.QFrame(self.frame_4)
		self.frame_5.setGeometry(QtCore.QRect(20, 20, 811, 311))
		self.frame_5.setStyleSheet("QFrame#frame_5{\n"
"    background-color: rgb(162, 162, 162);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QLineEdit{\n"
"    padding: 5px;\n"
"    border: 1px solid rgb(208, 208, 191);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border-left: 3px solid qlineargradient(spread:reflect, x1:0, y1:0.5, x2:1, y2:0.494, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-top: 3px solid qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0.494, y2:1, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-right: 3px solid qlineargradient(spread:reflect, x1:0, y1:0.5, x2:1, y2:0.494, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-bottom: 3px solid qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0.494, y2:1, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px;\n"
"      color:rgb(0, 70, 213)\n"
"}\n"
"\n"
"\n"
"\n"
"")
		self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_5.setObjectName("frame_5")
		self.groupBox_3 = QtWidgets.QGroupBox(self.frame_5)
		self.groupBox_3.setGeometry(QtCore.QRect(490, 160, 311, 101))
		self.groupBox_3.setObjectName("groupBox_3")
		self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
		self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 291, 65))
		self.layoutWidget.setObjectName("layoutWidget")
		self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
		self.gridLayout.setContentsMargins(0, 0, 0, 0)
		self.gridLayout.setObjectName("gridLayout")
		self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox.setObjectName("checkBox")
		self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
		self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_4.setObjectName("checkBox_4")
		self.gridLayout.addWidget(self.checkBox_4, 0, 1, 1, 1)
		self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_7.setObjectName("checkBox_7")
		self.gridLayout.addWidget(self.checkBox_7, 0, 2, 1, 1)
		self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_9.setObjectName("checkBox_9")
		self.gridLayout.addWidget(self.checkBox_9, 0, 3, 1, 1)
		self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_11.setObjectName("checkBox_11")
		self.gridLayout.addWidget(self.checkBox_11, 0, 4, 1, 1)
		self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_13.setObjectName("checkBox_13")
		self.gridLayout.addWidget(self.checkBox_13, 0, 5, 1, 1)
		self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_2.setObjectName("checkBox_2")
		self.gridLayout.addWidget(self.checkBox_2, 1, 0, 1, 1)
		self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_5.setObjectName("checkBox_5")
		self.gridLayout.addWidget(self.checkBox_5, 1, 1, 1, 1)
		self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_8.setObjectName("checkBox_8")
		self.gridLayout.addWidget(self.checkBox_8, 1, 2, 1, 1)
		self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_10.setObjectName("checkBox_10")
		self.gridLayout.addWidget(self.checkBox_10, 1, 3, 1, 1)
		self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_12.setObjectName("checkBox_12")
		self.gridLayout.addWidget(self.checkBox_12, 1, 4, 1, 1)
		self.checkBox_14 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_14.setObjectName("checkBox_14")
		self.gridLayout.addWidget(self.checkBox_14, 1, 5, 1, 1)
		self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_3.setObjectName("checkBox_3")
		self.gridLayout.addWidget(self.checkBox_3, 2, 0, 1, 1)
		self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget)
		self.checkBox_6.setObjectName("checkBox_6")
		self.gridLayout.addWidget(self.checkBox_6, 2, 1, 1, 1)
		self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
		self.pushButton_3.setGeometry(QtCore.QRect(540, 270, 75, 23))
		self.pushButton_3.setObjectName("pushButton_3")
		self.pushButton = QtWidgets.QPushButton(self.frame_5)
		self.pushButton.setGeometry(QtCore.QRect(720, 270, 75, 23))
		self.pushButton.setObjectName("pushButton")
		self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
		self.pushButton_2.setGeometry(QtCore.QRect(630, 270, 75, 23))
		self.pushButton_2.setObjectName("pushButton_2")
		self.groupBox = QtWidgets.QGroupBox(self.frame_5)
		self.groupBox.setGeometry(QtCore.QRect(10, 10, 471, 251))
		self.groupBox.setObjectName("groupBox")
		self.frame_7 = QtWidgets.QFrame(self.groupBox)
		self.frame_7.setGeometry(QtCore.QRect(240, 100, 221, 31))
		self.frame_7.setStyleSheet("QFrame#frame_7{\n"
"    padding: 5px;\n"
"    border: 1px solid rgb(208, 208, 191);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"}")
		self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_7.setObjectName("frame_7")
		self.radioButton = QtWidgets.QRadioButton(self.frame_7)
		self.radioButton.setGeometry(QtCore.QRect(10, 8, 55, 17))
		self.radioButton.setObjectName("radioButton")
		self.radioButton_2 = QtWidgets.QRadioButton(self.frame_7)
		self.radioButton_2.setGeometry(QtCore.QRect(70, 8, 100, 17))
		self.radioButton_2.setObjectName("radioButton_2")
		self.radioButton_3 = QtWidgets.QRadioButton(self.frame_7)
		self.radioButton_3.setGeometry(QtCore.QRect(140, 8, 71, 17))
		self.radioButton_3.setObjectName("radioButton_3")
		self.frame_8 = QtWidgets.QFrame(self.groupBox)
		self.frame_8.setGeometry(QtCore.QRect(10, 160, 451, 31))
		self.frame_8.setStyleSheet("QFrame#frame_8{\n"
"    padding: 5px;\n"
"    border: 1px solid rgb(208, 208, 191);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 6px;\n"
"}")
		self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_8.setObjectName("frame_8")
		self.label_5 = QtWidgets.QLabel(self.frame_8)
		self.label_5.setGeometry(QtCore.QRect(10, 6, 41, 18))
		self.label_5.setObjectName("label_5")
		self.dateEdit = QtWidgets.QDateEdit(self.frame_8)
		self.dateEdit.setGeometry(QtCore.QRect(60, 6, 151, 20))
		self.dateEdit.setObjectName("dateEdit")
		self.label_6 = QtWidgets.QLabel(self.frame_8)
		self.label_6.setGeometry(QtCore.QRect(230, 6, 31, 18))
		self.label_6.setObjectName("label_6")
		self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_8)
		self.dateEdit_2.setGeometry(QtCore.QRect(273, 6, 171, 20))
		self.dateEdit_2.setObjectName("dateEdit_2")
		self.label_4 = QtWidgets.QLabel(self.groupBox)
		self.label_4.setGeometry(QtCore.QRect(250, 80, 28, 16))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_4.setFont(font)
		self.label_4.setObjectName("label_4")
		self.label_7 = QtWidgets.QLabel(self.groupBox)
		self.label_7.setGeometry(QtCore.QRect(20, 140, 116, 16))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_7.setFont(font)
		self.label_7.setObjectName("label_7")
		self.label_3 = QtWidgets.QLabel(self.groupBox)
		self.label_3.setGeometry(QtCore.QRect(20, 80, 65, 16))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_3.setFont(font)
		self.label_3.setObjectName("label_3")
		self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
		self.lineEdit_2.setGeometry(QtCore.QRect(10, 100, 211, 31))
		self.lineEdit_2.setObjectName("lineEdit_2")
		self.label = QtWidgets.QLabel(self.groupBox)
		self.label.setGeometry(QtCore.QRect(20, 23, 44, 16))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
		self.lineEdit.setGeometry(QtCore.QRect(10, 40, 211, 31))
		self.lineEdit.setObjectName("lineEdit")
		self.label_2 = QtWidgets.QLabel(self.groupBox)
		self.label_2.setGeometry(QtCore.QRect(250, 20, 81, 16))
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		self.label_2.setFont(font)
		self.label_2.setObjectName("label_2")
		self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
		self.lineEdit_3.setGeometry(QtCore.QRect(240, 40, 221, 31))
		self.lineEdit_3.setObjectName("lineEdit_3")
		self.groupBox_2 = QtWidgets.QGroupBox(self.frame_5)
		self.groupBox_2.setGeometry(QtCore.QRect(490, 10, 311, 141))
		self.groupBox_2.setObjectName("groupBox_2")
		self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
		self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 101, 111))
		self.layoutWidget_3.setObjectName("layoutWidget_3")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
		self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget_3)
		self.radioButton_4.setObjectName("radioButton_4")
		self.verticalLayout_7.addWidget(self.radioButton_4)
		self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget_3)
		self.radioButton_5.setObjectName("radioButton_5")
		self.verticalLayout_7.addWidget(self.radioButton_5)
		self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget_3)
		self.radioButton_6.setObjectName("radioButton_6")
		self.verticalLayout_7.addWidget(self.radioButton_6)
		self.radioButton_7 = QtWidgets.QRadioButton(self.layoutWidget_3)
		self.radioButton_7.setObjectName("radioButton_7")
		self.verticalLayout_7.addWidget(self.radioButton_7)
		self.radioButton_8 = QtWidgets.QRadioButton(self.layoutWidget_3)
		self.radioButton_8.setObjectName("radioButton_8")
		self.verticalLayout_7.addWidget(self.radioButton_8)
		self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
		self.layoutWidget_4.setGeometry(QtCore.QRect(130, 20, 171, 91))
		self.layoutWidget_4.setObjectName("layoutWidget_4")
		self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
		self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_8.setObjectName("verticalLayout_8")
		self.radioButton_9 = QtWidgets.QRadioButton(self.layoutWidget_4)
		self.radioButton_9.setObjectName("radioButton_9")
		self.verticalLayout_8.addWidget(self.radioButton_9)
		self.dateEdit_3 = QtWidgets.QDateEdit(self.layoutWidget_4)
		self.dateEdit_3.setObjectName("dateEdit_3")
		self.verticalLayout_8.addWidget(self.dateEdit_3)
		self.dateEdit_4 = QtWidgets.QDateEdit(self.layoutWidget_4)
		self.dateEdit_4.setObjectName("dateEdit_4")
		self.verticalLayout_8.addWidget(self.dateEdit_4)
		self.frame_6 = QtWidgets.QFrame(self.frame_4)
		self.frame_6.setGeometry(QtCore.QRect(840, 20, 451, 311))
		self.frame_6.setStyleSheet("QFrame#frame_6{\n"
"    background-color: rgb(162, 162, 162);\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border-left: 3px solid qlineargradient(spread:reflect, x1:0, y1:0.5, x2:1, y2:0.494, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-top: 3px solid qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0.494, y2:1, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-right: 3px solid qlineargradient(spread:reflect, x1:0, y1:0.5, x2:1, y2:0.494, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-bottom: 3px solid qlineargradient(spread:reflect, x1:0.488636, y1:0, x2:0.494, y2:1, stop:0.293785 rgba(255, 255, 255, 255), stop:0.338983 rgba(211, 211, 211, 255), stop:0.683616 rgba(211, 211, 211, 255), stop:0.717514 rgba(255, 255, 255, 255));\n"
"    border-radius: 5px;\n"
"    margin-top: 2ex; /* leave space at the top for the title */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px;\n"
"      color:rgb(0, 70, 213)\n"
"}\n"
"\n"
"\n"
"\n"
"")
		self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_6.setObjectName("frame_6")
		self.groupBox_4 = QtWidgets.QGroupBox(self.frame_6)
		self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 421, 251))
		self.groupBox_4.setObjectName("groupBox_4")
		self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
		self.tableWidget.setGeometry(QtCore.QRect(10, 20, 401, 221))
		self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(197, 197, 197);\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494, y2:0, stop:0 rgba(117, 160, 229, 255), stop:1 rgba(233, 238, 248, 255));\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    border:none;\n"
"    border-left: 1px solid #6c6c6c;\n"
"}\n"
"")
		self.tableWidget.setObjectName("tableWidget")
		self.tableWidget.setColumnCount(5)
		self.tableWidget.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		item.setFont(font)
		self.tableWidget.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_4)
		self.tableWidget_2.setGeometry(QtCore.QRect(20, 350, 1261, 241))
		self.tableWidget_2.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(197, 197, 197);\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494, y2:0, stop:0 rgba(117, 160, 229, 255), stop:1 rgba(233, 238, 248, 255));\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    border:none;\n"
"    border-left: 1px solid #6c6c6c;\n"
"}\n"
"")
		self.tableWidget_2.setObjectName("tableWidget_2")
		self.tableWidget_2.setColumnCount(8)
		self.tableWidget_2.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_2.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_2.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_2.setHorizontalHeaderItem(4, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_2.setHorizontalHeaderItem(5, item)
		item = QtWidgets.QTableWidgetItem()
		font = QtGui.QFont()
		font.setBold(True)
		font.setWeight(75)
		item.setFont(font)
		self.tableWidget_2.setHorizontalHeaderItem(6, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_2.setHorizontalHeaderItem(7, item)
		self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
		self.tabWidget.addTab(self.tab_2, "")
		self.frame_2 = QtWidgets.QFrame(self.frame)
		self.frame_2.setGeometry(QtCore.QRect(0, 0, 1261, 41))
		self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color: qradialgradient(spread:pad, cx:0.484, cy:1, radius:1, fx:0.467, fy:1, stop:0 rgba(114, 114, 114, 255), stop:1 rgba(0, 0, 0, 255));\n"
"}")
		self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_2.setObjectName("frame_2")
		self.frame_2.raise_()
		self.tabWidget.raise_()

		self.retranslateUi(Dialog)
		self.tabWidget.setCurrentIndex(0)
		self.tabWidget_2.setCurrentIndex(2)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "                                                                                                                                                                               Bandeja de casos"))
		self.label_8.setText(_translate("Dialog", "Gestión local"))
		self.toolButton_4.setText(_translate("Dialog", "Abrir\n"
"DICOM"))
		self.toolButton_5.setText(_translate("Dialog", "Abrir \n"
"carpeta"))
		self.toolButton.setText(_translate("Dialog", "Eliminar\n"
""))
		self.label_9.setText(_translate("Dialog", "Enviar"))
		self.toolButton_2.setText(_translate("Dialog", "Enviar a\n"
"visor activo"))
		self.toolButton_3.setText(_translate("Dialog", "  Enviar a\n"
"nuevo visor"))
		self.toolButton_6.setText(_translate("Dialog", "Enviar\n"
"a nodo"))
		self.toolButton_7.setText(_translate("Dialog", "Enviar a\n"
"DMail"))
		self.label_10.setText(_translate("Dialog", "Exportar"))
		self.toolButton_8.setText(_translate("Dialog", " Quemar"))
		self.toolButton_9.setText(_translate("Dialog", "Exportar a\n"
"dispositivo"))
		self.label_11.setText(_translate("Dialog", "Configurar"))
		self.toolButton_10.setText(_translate("Dialog", "Configuración"))
		self.label_12.setText(_translate("Dialog", "Buscar pacientes"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Dialog", "Nombre del paciente"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Dialog", "Identificador del paciente"))
		self.radioButton_10.setText(_translate("Dialog", "Ambos"))
		self.radioButton_11.setText(_translate("Dialog", "Masculino"))
		self.radioButton_12.setText(_translate("Dialog", "Femenino"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Dialog", "Sexo"))
		item = self.tableWidget_3.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "Nombre del paciente"))
		item = self.tableWidget_3.horizontalHeaderItem(3)
		item.setText(_translate("Dialog", "Identificador del paciente"))
		item = self.tableWidget_3.horizontalHeaderItem(4)
		item.setText(_translate("Dialog", "Fecha de nacimiento"))
		item = self.tableWidget_3.horizontalHeaderItem(5)
		item.setText(_translate("Dialog", "Sexo"))
		item = self.tableWidget_3.horizontalHeaderItem(6)
		item.setText(_translate("Dialog", "Imágenes"))
		item = self.tableWidget_3.horizontalHeaderItem(7)
		item.setText(_translate("Dialog", "Institución de origen"))
		self.groupBox_5.setTitle(_translate("Dialog", "Series"))
		item = self.tableWidget_4.horizontalHeaderItem(0)
		item.setText(_translate("Dialog", "Nombre del paciente"))
		item = self.tableWidget_4.horizontalHeaderItem(2)
		item.setText(_translate("Dialog", "Modalidad"))
		item = self.tableWidget_4.horizontalHeaderItem(3)
		item.setText(_translate("Dialog", "Imágenes"))
		item = self.tableWidget_4.horizontalHeaderItem(4)
		item.setText(_translate("Dialog", "Fecha"))
		item = self.tableWidget_4.horizontalHeaderItem(5)
		item.setText(_translate("Dialog", "Descripción"))
		self.groupBox_6.setTitle(_translate("Dialog", "Imágenes"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", " Pacientes locales "))
		self.groupBox_3.setTitle(_translate("Dialog", "Modalidad"))
		self.checkBox.setText(_translate("Dialog", "Todas"))
		self.checkBox_4.setText(_translate("Dialog", "CT"))
		self.checkBox_7.setText(_translate("Dialog", "MR"))
		self.checkBox_9.setText(_translate("Dialog", "US"))
		self.checkBox_11.setText(_translate("Dialog", "XA"))
		self.checkBox_13.setText(_translate("Dialog", "MG"))
		self.checkBox_2.setText(_translate("Dialog", "CR"))
		self.checkBox_5.setText(_translate("Dialog", "DX"))
		self.checkBox_8.setText(_translate("Dialog", "OT"))
		self.checkBox_10.setText(_translate("Dialog", "NM"))
		self.checkBox_12.setText(_translate("Dialog", "RF"))
		self.checkBox_14.setText(_translate("Dialog", "SR"))
		self.checkBox_3.setText(_translate("Dialog", "IO"))
		self.checkBox_6.setText(_translate("Dialog", "PX"))
		self.pushButton_3.setText(_translate("Dialog", "Buscar"))
		self.pushButton.setText(_translate("Dialog", "Limpiar"))
		self.pushButton_2.setText(_translate("Dialog", "Detener"))
		self.groupBox.setTitle(_translate("Dialog", "Datos del paciente"))
		self.radioButton.setText(_translate("Dialog", "Ambos"))
		self.radioButton_2.setText(_translate("Dialog", "Masculino"))
		self.radioButton_3.setText(_translate("Dialog", "Femenino"))
		self.label_5.setText(_translate("Dialog", "Desde:"))
		self.label_6.setText(_translate("Dialog", "Hasta:"))
		self.label_4.setText(_translate("Dialog", "Sexo"))
		self.label_7.setText(_translate("Dialog", "Fecha de nacimiento"))
		self.label_3.setText(_translate("Dialog", "Descripción"))
		self.label.setText(_translate("Dialog", "Nombre"))
		self.label_2.setText(_translate("Dialog", "Id de paciente"))
		self.groupBox_2.setTitle(_translate("Dialog", "Fecha del estudio"))
		self.radioButton_4.setText(_translate("Dialog", "Cualquier día"))
		self.radioButton_5.setText(_translate("Dialog", "Hoy"))
		self.radioButton_6.setText(_translate("Dialog", "Ayer"))
		self.radioButton_7.setText(_translate("Dialog", "Semana pasada"))
		self.radioButton_8.setText(_translate("Dialog", "Mes pasado"))
		self.radioButton_9.setText(_translate("Dialog", "Entre"))
		self.groupBox_4.setTitle(_translate("Dialog", "Servidores"))
		item = self.tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("Dialog", "Nombre del nodo"))
		item = self.tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "Título EA"))
		item = self.tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("Dialog", "IP"))
		item = self.tableWidget.horizontalHeaderItem(3)
		item.setText(_translate("Dialog", "Puerto"))
		item = self.tableWidget.horizontalHeaderItem(4)
		item.setText(_translate("Dialog", "Conexión"))
		item = self.tableWidget_2.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "Nombre del paciente"))
		item = self.tableWidget_2.horizontalHeaderItem(3)
		item.setText(_translate("Dialog", "Identificador del paciente"))
		item = self.tableWidget_2.horizontalHeaderItem(4)
		item.setText(_translate("Dialog", "Fecha de nacimiento"))
		item = self.tableWidget_2.horizontalHeaderItem(5)
		item.setText(_translate("Dialog", ""))
		item = self.tableWidget_2.horizontalHeaderItem(6)
		item.setText(_translate("Dialog", "Institución de origen"))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", " Búsqueda/Obtención "))
import assets.resources
