# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Configuración.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Configuracion(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.resize(630, 486)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/bandeja_de_casos/assets/bandeja_de_casos/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		Dialog.setWindowIcon(icon)
		self.frame = QtWidgets.QFrame(Dialog)
		self.frame.setGeometry(QtCore.QRect(0, 0, 631, 31))
		self.frame.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.484, cy:1, radius:1, fx:0.467, fy:1, stop:0 rgba(114, 114, 114, 255), stop:1 rgba(0, 0, 0, 255));\n"
"border-bottom: 3px solid qlineargradient(spread:pad, x1:0, y1:0.5625, x2:1, y2:0.517045, stop:0 rgba(0, 96, 0, 255), stop:1 rgba(244, 244, 244, 255));")
		self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame.setObjectName("frame")
		self.frame_2 = QtWidgets.QFrame(Dialog)
		self.frame_2.setGeometry(QtCore.QRect(0, 30, 141, 401))
		self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.539773, y1:1, x2:0.545455, y2:0, stop:0 rgba(59, 59, 59, 255), stop:1 rgba(112, 112, 112, 255));\n"
"\n"
"")
		self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_2.setObjectName("frame_2")
		self.pushButton = QtWidgets.QPushButton(self.frame_2)
		self.pushButton.setGeometry(QtCore.QRect(0, 10, 141, 41))
		self.pushButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: rgb(191, 223, 191);\n"
"}\n"
"QPushButton:checked{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: qradialgradient(spread:pad, cx:0.511364, cy:1, radius:0.99, fx:0.505682, fy:1, stop:0 rgba(157, 206, 157, 255), stop:1 rgba(0, 128, 0, 255));\n"
"}")
		self.pushButton.setCheckable(False)
		self.pushButton.setChecked(False)
		self.pushButton.setObjectName("pushButton")
		self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
		self.pushButton_2.setGeometry(QtCore.QRect(0, 60, 141, 41))
		self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: rgb(191, 223, 191);\n"
"}\n"
"QPushButton:checked{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: qradialgradient(spread:pad, cx:0.511364, cy:1, radius:0.99, fx:0.505682, fy:1, stop:0 rgba(157, 206, 157, 255), stop:1 rgba(0, 128, 0, 255));\n"
"}")
		self.pushButton_2.setCheckable(False)
		self.pushButton_2.setChecked(False)
		self.pushButton_2.setObjectName("pushButton_2")
		self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
		self.pushButton_3.setGeometry(QtCore.QRect(0, 110, 141, 41))
		self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: rgb(191, 223, 191);\n"
"}\n"
"QPushButton:checked{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: qradialgradient(spread:pad, cx:0.511364, cy:1, radius:0.99, fx:0.505682, fy:1, stop:0 rgba(157, 206, 157, 255), stop:1 rgba(0, 128, 0, 255));\n"
"}")
		self.pushButton_3.setCheckable(False)
		self.pushButton_3.setChecked(False)
		self.pushButton_3.setObjectName("pushButton_3")
		self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
		self.pushButton_4.setGeometry(QtCore.QRect(0, 160, 141, 41))
		self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: rgb(191, 223, 191);\n"
"}\n"
"QPushButton:checked{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: qradialgradient(spread:pad, cx:0.511364, cy:1, radius:0.99, fx:0.505682, fy:1, stop:0 rgba(157, 206, 157, 255), stop:1 rgba(0, 128, 0, 255));\n"
"}")
		self.pushButton_4.setCheckable(False)
		self.pushButton_4.setChecked(False)
		self.pushButton_4.setObjectName("pushButton_4")
		self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
		self.pushButton_5.setGeometry(QtCore.QRect(0, 210, 141, 41))
		self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: rgb(191, 223, 191);\n"
"}\n"
"QPushButton:checked{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: qradialgradient(spread:pad, cx:0.511364, cy:1, radius:0.99, fx:0.505682, fy:1, stop:0 rgba(157, 206, 157, 255), stop:1 rgba(0, 128, 0, 255));\n"
"}")
		self.pushButton_5.setCheckable(False)
		self.pushButton_5.setChecked(False)
		self.pushButton_5.setObjectName("pushButton_5")
		self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
		self.pushButton_6.setGeometry(QtCore.QRect(0, 260, 141, 41))
		self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: rgb(191, 223, 191);\n"
"}\n"
"QPushButton:checked{\n"
"    border-top: 1px solid rgb(0, 64, 0);\n"
"    border-bottom: 1px solid rgb(0, 64, 0);\n"
"    background-color: qradialgradient(spread:pad, cx:0.511364, cy:1, radius:0.99, fx:0.505682, fy:1, stop:0 rgba(157, 206, 157, 255), stop:1 rgba(0, 128, 0, 255));\n"
"}")
		self.pushButton_6.setCheckable(False)
		self.pushButton_6.setChecked(False)
		self.pushButton_6.setObjectName("pushButton_6")
		self.frame_3 = QtWidgets.QFrame(Dialog)
		self.frame_3.setGeometry(QtCore.QRect(120, 30, 511, 401))
		self.frame_3.setStyleSheet("background-color: transparent;")
		self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_3.setObjectName("frame_3")
		self.stackedWidget = QtWidgets.QStackedWidget(self.frame_3)
		self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 511, 400))
		self.stackedWidget.setObjectName("stackedWidget")
		self.page = QtWidgets.QWidget()
		self.page.setObjectName("page")
		self.frame_5 = QtWidgets.QFrame(self.page)
		self.frame_5.setGeometry(QtCore.QRect(0, 10, 21, 41))
		self.frame_5.setStyleSheet("background-color: qconicalgradient(cx:0.663, cy:0.511, angle:90.9, stop:0.351648 rgba(255, 255, 255, 0), stop:0.664773 rgba(255, 255, 255, 0), stop:0.670455 rgba(240, 240, 240, 255), stop:0.823864 rgba(240, 240, 240, 255), stop:0.829545 rgba(255, 255, 255, 0));")
		self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_5.setObjectName("frame_5")
		self.frame_11 = QtWidgets.QFrame(self.page)
		self.frame_11.setGeometry(QtCore.QRect(20, 0, 491, 401))
		self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_11.setObjectName("frame_11")
		self.frame_12 = QtWidgets.QFrame(self.frame_11)
		self.frame_12.setGeometry(QtCore.QRect(0, 0, 491, 401))
		self.frame_12.setStyleSheet("background-color: rgb(245, 245, 245);")
		self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_12.setObjectName("frame_12")
		self.groupBox_3 = QtWidgets.QGroupBox(self.frame_12)
		self.groupBox_3.setGeometry(QtCore.QRect(10, 160, 471, 71))
		self.groupBox_3.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_3.setObjectName("groupBox_3")
		self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
		self.radioButton.setGeometry(QtCore.QRect(40, 30, 82, 17))
		self.radioButton.setStyleSheet("color: rgb(0, 0, 0);")
		self.radioButton.setObjectName("radioButton")
		self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
		self.radioButton_2.setGeometry(QtCore.QRect(230, 30, 82, 17))
		self.radioButton_2.setStyleSheet("color: rgb(0, 0, 0);")
		self.radioButton_2.setObjectName("radioButton_2")
		self.groupBox_4 = QtWidgets.QGroupBox(self.frame_12)
		self.groupBox_4.setGeometry(QtCore.QRect(10, 240, 471, 141))
		self.groupBox_4.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_4.setObjectName("groupBox_4")
		self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
		self.tableWidget.setGeometry(QtCore.QRect(10, 20, 311, 111))
		self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494, y2:0, stop:0 rgba(117, 160, 229, 255), stop:1 rgba(233, 238, 248, 255));\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    border:none;\n"
"    border-left: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    color: black;\n"
"}\n"
"\n"
"")
		self.tableWidget.setObjectName("tableWidget")
		self.tableWidget.setColumnCount(3)
		self.tableWidget.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget.setHorizontalHeaderItem(2, item)
		self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_4)
		self.pushButton_10.setGeometry(QtCore.QRect(330, 52, 121, 31))
		self.pushButton_10.setStyleSheet("QPushButton#pushButton_10{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton#pushButton_10:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton#pushButton_10:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"")
		self.pushButton_10.setCheckable(False)
		self.pushButton_10.setChecked(False)
		self.pushButton_10.setObjectName("pushButton_10")
		self.groupBox_2 = QtWidgets.QGroupBox(self.frame_12)
		self.groupBox_2.setGeometry(QtCore.QRect(10, 80, 471, 71))
		self.groupBox_2.setStyleSheet("color: rgb(56, 56, 250);")
		self.groupBox_2.setObjectName("groupBox_2")
		self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
		self.comboBox.setGeometry(QtCore.QRect(10, 30, 451, 22))
		self.comboBox.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}\n"
"\n"
"")
		self.comboBox.setEditable(False)
		self.comboBox.setObjectName("comboBox")
		self.comboBox.addItem("")
		self.groupBox = QtWidgets.QGroupBox(self.frame_12)
		self.groupBox.setGeometry(QtCore.QRect(10, 10, 471, 61))
		self.groupBox.setStyleSheet("")
		self.groupBox.setTitle("")
		self.groupBox.setObjectName("groupBox")
		self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
		self.lineEdit.setGeometry(QtCore.QRect(10, 30, 201, 20))
		self.lineEdit.setStyleSheet("QLineEdit{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(171, 173, 179);\n"
"    border-radius: 0px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    border-radius: 0px;\n"
"}\n"
"")
		self.lineEdit.setObjectName("lineEdit")
		self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
		self.lineEdit_2.setGeometry(QtCore.QRect(220, 30, 241, 20))
		self.lineEdit_2.setStyleSheet("border: 1px solid rgb(204, 204, 187);")
		self.lineEdit_2.setObjectName("lineEdit_2")
		self.label = QtWidgets.QLabel(self.groupBox)
		self.label.setGeometry(QtCore.QRect(10, 10, 101, 16))
		self.label.setStyleSheet("color: rgb(0, 0, 255);\n"
"border: none;")
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(self.groupBox)
		self.label_2.setGeometry(QtCore.QRect(220, 10, 47, 13))
		self.label_2.setStyleSheet("color: rgb(0, 0, 255);\n"
"border: none;")
		self.label_2.setObjectName("label_2")
		self.stackedWidget.addWidget(self.page)
		self.page_2 = QtWidgets.QWidget()
		self.page_2.setObjectName("page_2")
		self.frame_6 = QtWidgets.QFrame(self.page_2)
		self.frame_6.setGeometry(QtCore.QRect(0, 60, 21, 41))
		self.frame_6.setStyleSheet("background-color: qconicalgradient(cx:0.663, cy:0.511, angle:90.9, stop:0.351648 rgba(255, 255, 255, 0), stop:0.664773 rgba(255, 255, 255, 0), stop:0.670455 rgba(240, 240, 240, 255), stop:0.823864 rgba(240, 240, 240, 255), stop:0.829545 rgba(255, 255, 255, 0));")
		self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_6.setObjectName("frame_6")
		self.frame_13 = QtWidgets.QFrame(self.page_2)
		self.frame_13.setGeometry(QtCore.QRect(20, -1, 491, 401))
		self.frame_13.setStyleSheet("background-color: rgb(245, 245, 245);")
		self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_13.setObjectName("frame_13")
		self.pushButton_11 = QtWidgets.QPushButton(self.frame_13)
		self.pushButton_11.setGeometry(QtCore.QRect(290, 160, 151, 31))
		self.pushButton_11.setStyleSheet("QPushButton#pushButton_11{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton#pushButton_11:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton#pushButton_10:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"")
		self.pushButton_11.setObjectName("pushButton_11")
		self.groupBox_7 = QtWidgets.QGroupBox(self.frame_13)
		self.groupBox_7.setGeometry(QtCore.QRect(250, 10, 231, 121))
		self.groupBox_7.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_7.setObjectName("groupBox_7")
		self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_7)
		self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 211, 91))
		self.layoutWidget_2.setObjectName("layoutWidget_2")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_7.setObjectName("horizontalLayout_7")
		self.label_11 = QtWidgets.QLabel(self.layoutWidget_2)
		self.label_11.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_11.setObjectName("label_11")
		self.horizontalLayout_7.addWidget(self.label_11)
		self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget_2)
		self.comboBox_7.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_7.setObjectName("comboBox_7")
		self.comboBox_7.addItem("")
		self.horizontalLayout_7.addWidget(self.comboBox_7)
		self.verticalLayout_4.addLayout(self.horizontalLayout_7)
		self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.label_12 = QtWidgets.QLabel(self.layoutWidget_2)
		self.label_12.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_12.setObjectName("label_12")
		self.horizontalLayout_8.addWidget(self.label_12)
		self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget_2)
		self.comboBox_8.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_8.setObjectName("comboBox_8")
		self.comboBox_8.addItem("")
		self.horizontalLayout_8.addWidget(self.comboBox_8)
		self.verticalLayout_4.addLayout(self.horizontalLayout_8)
		self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_9.setObjectName("horizontalLayout_9")
		self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
		self.label_13.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_13.setObjectName("label_13")
		self.horizontalLayout_9.addWidget(self.label_13)
		self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget_2)
		self.spinBox_3.setStyleSheet("color: rgb(0, 0, 0);")
		self.spinBox_3.setObjectName("spinBox_3")
		self.horizontalLayout_9.addWidget(self.spinBox_3)
		self.verticalLayout_4.addLayout(self.horizontalLayout_9)
		self.groupBox_8 = QtWidgets.QGroupBox(self.frame_13)
		self.groupBox_8.setGeometry(QtCore.QRect(10, 140, 231, 61))
		self.groupBox_8.setObjectName("groupBox_8")
		self.line_7 = QtWidgets.QFrame(self.groupBox_8)
		self.line_7.setGeometry(QtCore.QRect(20, 30, 151, 20))
		self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
		self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
		self.line_7.setObjectName("line_7")
		self.groupBox_6 = QtWidgets.QGroupBox(self.frame_13)
		self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 231, 121))
		self.groupBox_6.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_6.setObjectName("groupBox_6")
		self.layoutWidget = QtWidgets.QWidget(self.groupBox_6)
		self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 91))
		self.layoutWidget.setObjectName("layoutWidget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.label_3 = QtWidgets.QLabel(self.layoutWidget)
		self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_3.setObjectName("label_3")
		self.horizontalLayout.addWidget(self.label_3)
		self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
		self.comboBox_2.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_2.setObjectName("comboBox_2")
		self.comboBox_2.addItem("")
		self.horizontalLayout.addWidget(self.comboBox_2)
		self.verticalLayout_2.addLayout(self.horizontalLayout)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.label_4 = QtWidgets.QLabel(self.layoutWidget)
		self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_4.setObjectName("label_4")
		self.horizontalLayout_2.addWidget(self.label_4)
		self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
		self.comboBox_3.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_3.setObjectName("comboBox_3")
		self.comboBox_3.addItem("")
		self.horizontalLayout_2.addWidget(self.comboBox_3)
		self.verticalLayout_2.addLayout(self.horizontalLayout_2)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.label_5 = QtWidgets.QLabel(self.layoutWidget)
		self.label_5.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_5.setObjectName("label_5")
		self.horizontalLayout_3.addWidget(self.label_5)
		self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
		self.spinBox.setStyleSheet("color: rgb(0, 0, 0);")
		self.spinBox.setObjectName("spinBox")
		self.horizontalLayout_3.addWidget(self.spinBox)
		self.verticalLayout_2.addLayout(self.horizontalLayout_3)
		self.stackedWidget.addWidget(self.page_2)
		self.page_3 = QtWidgets.QWidget()
		self.page_3.setObjectName("page_3")
		self.frame_7 = QtWidgets.QFrame(self.page_3)
		self.frame_7.setGeometry(QtCore.QRect(0, 110, 21, 41))
		self.frame_7.setStyleSheet("background-color: qconicalgradient(cx:0.663, cy:0.511, angle:90.9, stop:0.351648 rgba(255, 255, 255, 0), stop:0.664773 rgba(255, 255, 255, 0), stop:0.670455 rgba(240, 240, 240, 255), stop:0.823864 rgba(240, 240, 240, 255), stop:0.829545 rgba(255, 255, 255, 0));")
		self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_7.setObjectName("frame_7")
		self.frame_14 = QtWidgets.QFrame(self.page_3)
		self.frame_14.setGeometry(QtCore.QRect(20, -1, 491, 401))
		self.frame_14.setStyleSheet("background-color: rgb(245, 245, 245);")
		self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_14.setObjectName("frame_14")
		self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_14)
		self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 491, 451))
		self.tabWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
		self.tabWidget_2.setObjectName("tabWidget_2")
		self.tab_general_2 = QtWidgets.QWidget()
		self.tab_general_2.setObjectName("tab_general_2")
		self.groupBox_20 = QtWidgets.QGroupBox(self.tab_general_2)
		self.groupBox_20.setGeometry(QtCore.QRect(20, 10, 351, 71))
		self.groupBox_20.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_20.setObjectName("groupBox_20")
		self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_20)
		self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 331, 30))
		self.layoutWidget1.setObjectName("layoutWidget1")
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget1)
		self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget1)
		self.lineEdit_6.setMinimumSize(QtCore.QSize(58, 25))
		self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
		self.lineEdit_6.setStyleSheet("border: 1px solid rgb(208, 208, 191);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
		self.lineEdit_6.setObjectName("lineEdit_6")
		self.horizontalLayout_4.addWidget(self.lineEdit_6)
		self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget1)
		self.pushButton_18.setMinimumSize(QtCore.QSize(68, 24))
		self.pushButton_18.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
		self.pushButton_18.setObjectName("pushButton_18")
		self.horizontalLayout_4.addWidget(self.pushButton_18)
		self.groupBox_21 = QtWidgets.QGroupBox(self.tab_general_2)
		self.groupBox_21.setGeometry(QtCore.QRect(380, 10, 91, 71))
		self.groupBox_21.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_21.setObjectName("groupBox_21")
		self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_21)
		self.spinBox_7.setGeometry(QtCore.QRect(17, 33, 61, 22))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(3)
		sizePolicy.setHeightForWidth(self.spinBox_7.sizePolicy().hasHeightForWidth())
		self.spinBox_7.setSizePolicy(sizePolicy)
		self.spinBox_7.setStyleSheet("color: rgb(0, 0, 0);")
		self.spinBox_7.setObjectName("spinBox_7")
		self.groupBox_22 = QtWidgets.QGroupBox(self.tab_general_2)
		self.groupBox_22.setGeometry(QtCore.QRect(20, 90, 451, 181))
		self.groupBox_22.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_22.setObjectName("groupBox_22")
		self.tableWidget_4 = QtWidgets.QTableWidget(self.groupBox_22)
		self.tableWidget_4.setGeometry(QtCore.QRect(10, 20, 431, 151))
		self.tableWidget_4.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494, y2:0, stop:0 rgba(117, 160, 229, 255), stop:1 rgba(233, 238, 248, 255));\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    border:none;\n"
"    border-left: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    color: black;\n"
"}\n"
"\n"
"")
		self.tableWidget_4.setObjectName("tableWidget_4")
		self.tableWidget_4.setColumnCount(5)
		self.tableWidget_4.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_4.setHorizontalHeaderItem(4, item)
		self.layoutWidget2 = QtWidgets.QWidget(self.tab_general_2)
		self.layoutWidget2.setGeometry(QtCore.QRect(170, 280, 301, 51))
		self.layoutWidget2.setObjectName("layoutWidget2")
		self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
		self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_5.setObjectName("horizontalLayout_5")
		self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget2)
		self.pushButton_21.setMinimumSize(QtCore.QSize(0, 29))
		self.pushButton_21.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
		self.pushButton_21.setObjectName("pushButton_21")
		self.horizontalLayout_5.addWidget(self.pushButton_21)
		self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget2)
		self.pushButton_20.setEnabled(False)
		self.pushButton_20.setMinimumSize(QtCore.QSize(0, 29))
		self.pushButton_20.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
		self.pushButton_20.setObjectName("pushButton_20")
		self.horizontalLayout_5.addWidget(self.pushButton_20)
		self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget2)
		self.pushButton_19.setEnabled(False)
		self.pushButton_19.setMinimumSize(QtCore.QSize(0, 29))
		self.pushButton_19.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
		self.pushButton_19.setObjectName("pushButton_19")
		self.horizontalLayout_5.addWidget(self.pushButton_19)
		self.tabWidget_2.addTab(self.tab_general_2, "")
		self.tab_envio_obtencion_2 = QtWidgets.QWidget()
		self.tab_envio_obtencion_2.setObjectName("tab_envio_obtencion_2")
		self.label_16 = QtWidgets.QLabel(self.tab_envio_obtencion_2)
		self.label_16.setGeometry(QtCore.QRect(20, 20, 221, 16))
		self.label_16.setObjectName("label_16")
		self.label_17 = QtWidgets.QLabel(self.tab_envio_obtencion_2)
		self.label_17.setGeometry(QtCore.QRect(20, 70, 241, 16))
		self.label_17.setObjectName("label_17")
		self.spinBox_8 = QtWidgets.QSpinBox(self.tab_envio_obtencion_2)
		self.spinBox_8.setGeometry(QtCore.QRect(260, 20, 51, 22))
		self.spinBox_8.setObjectName("spinBox_8")
		self.spinBox_9 = QtWidgets.QSpinBox(self.tab_envio_obtencion_2)
		self.spinBox_9.setGeometry(QtCore.QRect(260, 70, 51, 22))
		self.spinBox_9.setObjectName("spinBox_9")
		self.groupBox_23 = QtWidgets.QGroupBox(self.tab_envio_obtencion_2)
		self.groupBox_23.setGeometry(QtCore.QRect(20, 100, 291, 81))
		self.groupBox_23.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_23.setObjectName("groupBox_23")
		self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_23)
		self.radioButton_7.setGeometry(QtCore.QRect(20, 20, 191, 17))
		self.radioButton_7.setStyleSheet("color: rgb(0, 0, 0);")
		self.radioButton_7.setObjectName("radioButton_7")
		self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_23)
		self.radioButton_8.setGeometry(QtCore.QRect(20, 50, 191, 17))
		self.radioButton_8.setStyleSheet("color: rgb(0, 0, 0);")
		self.radioButton_8.setObjectName("radioButton_8")
		self.tabWidget_2.addTab(self.tab_envio_obtencion_2, "")
		self.stackedWidget.addWidget(self.page_3)
		self.page_4 = QtWidgets.QWidget()
		self.page_4.setObjectName("page_4")
		self.frame_8 = QtWidgets.QFrame(self.page_4)
		self.frame_8.setGeometry(QtCore.QRect(0, 160, 21, 41))
		self.frame_8.setStyleSheet("background-color: qconicalgradient(cx:0.663, cy:0.511, angle:90.9, stop:0.351648 rgba(255, 255, 255, 0), stop:0.664773 rgba(255, 255, 255, 0), stop:0.670455 rgba(240, 240, 240, 255), stop:0.823864 rgba(240, 240, 240, 255), stop:0.829545 rgba(255, 255, 255, 0));")
		self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_8.setObjectName("frame_8")
		self.tabWidget_3 = QtWidgets.QTabWidget(self.page_4)
		self.tabWidget_3.setGeometry(QtCore.QRect(20, 1, 491, 401))
		self.tabWidget_3.setStyleSheet("background-color: rgb(245, 245, 245);")
		self.tabWidget_3.setObjectName("tabWidget_3")
		self.tab_rep_general = QtWidgets.QWidget()
		self.tab_rep_general.setObjectName("tab_rep_general")
		self.groupBox_24 = QtWidgets.QGroupBox(self.tab_rep_general)
		self.groupBox_24.setGeometry(QtCore.QRect(10, 10, 471, 91))
		self.groupBox_24.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_24.setObjectName("groupBox_24")
		self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_24)
		self.radioButton_9.setGeometry(QtCore.QRect(20, 20, 82, 17))
		self.radioButton_9.setStyleSheet("color: rgb(0, 0, 0);")
		self.radioButton_9.setObjectName("radioButton_9")
		self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_24)
		self.radioButton_10.setGeometry(QtCore.QRect(20, 40, 161, 17))
		self.radioButton_10.setStyleSheet("color: rgb(0, 0, 0);")
		self.radioButton_10.setObjectName("radioButton_10")
		self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_24)
		self.radioButton_11.setGeometry(QtCore.QRect(20, 60, 161, 17))
		self.radioButton_11.setStyleSheet("color: rgb(0, 0, 0);")
		self.radioButton_11.setObjectName("radioButton_11")
		self.groupBox_25 = QtWidgets.QGroupBox(self.tab_rep_general)
		self.groupBox_25.setGeometry(QtCore.QRect(10, 110, 471, 71))
		self.groupBox_25.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_25.setObjectName("groupBox_25")
		self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_25)
		self.layoutWidget3.setGeometry(QtCore.QRect(20, 20, 441, 31))
		self.layoutWidget3.setObjectName("layoutWidget3")
		self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
		self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_6.setObjectName("horizontalLayout_6")
		self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
		self.label_18.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_18.setObjectName("label_18")
		self.horizontalLayout_6.addWidget(self.label_18)
		self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget3)
		self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 24))
		self.lineEdit_7.setStyleSheet("QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(171, 173, 179);\n"
"    border-radius: 0px;\n"
"}\n"
"QLineEdit:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    border-radius: 0px;\n"
"}\n"
"")
		self.lineEdit_7.setObjectName("lineEdit_7")
		self.horizontalLayout_6.addWidget(self.lineEdit_7)
		self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget3)
		self.pushButton_22.setMinimumSize(QtCore.QSize(0, 24))
		self.pushButton_22.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}")
		self.pushButton_22.setText("")
		self.pushButton_22.setObjectName("pushButton_22")
		self.horizontalLayout_6.addWidget(self.pushButton_22)
		self.groupBox_26 = QtWidgets.QGroupBox(self.tab_rep_general)
		self.groupBox_26.setGeometry(QtCore.QRect(10, 190, 471, 71))
		self.groupBox_26.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_26.setObjectName("groupBox_26")
		self.spinBox_10 = QtWidgets.QSpinBox(self.groupBox_26)
		self.spinBox_10.setGeometry(QtCore.QRect(20, 30, 71, 22))
		self.spinBox_10.setStyleSheet("color: rgb(0, 0, 0);")
		self.spinBox_10.setObjectName("spinBox_10")
		self.groupBox_27 = QtWidgets.QGroupBox(self.tab_rep_general)
		self.groupBox_27.setGeometry(QtCore.QRect(10, 270, 471, 91))
		self.groupBox_27.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_27.setObjectName("groupBox_27")
		self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_27)
		self.layoutWidget_3.setGeometry(QtCore.QRect(20, 20, 279, 26))
		self.layoutWidget_3.setObjectName("layoutWidget_3")
		self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
		self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_10.setObjectName("horizontalLayout_10")
		self.label_19 = QtWidgets.QLabel(self.layoutWidget_3)
		self.label_19.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_19.setObjectName("label_19")
		self.horizontalLayout_10.addWidget(self.label_19)
		self.spinBox_11 = QtWidgets.QSpinBox(self.layoutWidget_3)
		self.spinBox_11.setMinimumSize(QtCore.QSize(0, 24))
		self.spinBox_11.setStyleSheet("color: rgb(0, 0, 0);")
		self.spinBox_11.setObjectName("spinBox_11")
		self.horizontalLayout_10.addWidget(self.spinBox_11)
		self.label_20 = QtWidgets.QLabel(self.layoutWidget_3)
		self.label_20.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_20.setObjectName("label_20")
		self.horizontalLayout_10.addWidget(self.label_20)
		self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_27)
		self.layoutWidget_4.setGeometry(QtCore.QRect(20, 50, 310, 26))
		self.layoutWidget_4.setObjectName("layoutWidget_4")
		self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
		self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_11.setObjectName("horizontalLayout_11")
		self.label_21 = QtWidgets.QLabel(self.layoutWidget_4)
		self.label_21.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_21.setObjectName("label_21")
		self.horizontalLayout_11.addWidget(self.label_21)
		self.spinBox_12 = QtWidgets.QSpinBox(self.layoutWidget_4)
		self.spinBox_12.setMinimumSize(QtCore.QSize(0, 24))
		self.spinBox_12.setStyleSheet("color: rgb(0, 0, 0);")
		self.spinBox_12.setObjectName("spinBox_12")
		self.horizontalLayout_11.addWidget(self.spinBox_12)
		self.label_22 = QtWidgets.QLabel(self.layoutWidget_4)
		self.label_22.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_22.setObjectName("label_22")
		self.horizontalLayout_11.addWidget(self.label_22)
		self.tabWidget_3.addTab(self.tab_rep_general, "")
		self.tab_rep_pedales = QtWidgets.QWidget()
		self.tab_rep_pedales.setObjectName("tab_rep_pedales")
		self.groupBox_28 = QtWidgets.QGroupBox(self.tab_rep_pedales)
		self.groupBox_28.setGeometry(QtCore.QRect(10, 10, 471, 111))
		self.groupBox_28.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_28.setObjectName("groupBox_28")
		self.label_23 = QtWidgets.QLabel(self.groupBox_28)
		self.label_23.setGeometry(QtCore.QRect(10, 30, 71, 16))
		self.label_23.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_23.setObjectName("label_23")
		self.label_24 = QtWidgets.QLabel(self.groupBox_28)
		self.label_24.setGeometry(QtCore.QRect(10, 70, 71, 16))
		self.label_24.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_24.setObjectName("label_24")
		self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_28)
		self.comboBox_9.setGeometry(QtCore.QRect(110, 30, 271, 22))
		self.comboBox_9.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    text-align: right;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_9.setObjectName("comboBox_9")
		self.comboBox_9.addItem("")
		self.comboBox_10 = QtWidgets.QComboBox(self.groupBox_28)
		self.comboBox_10.setGeometry(QtCore.QRect(110, 70, 271, 22))
		self.comboBox_10.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    text-align: right;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_10.setObjectName("comboBox_10")
		self.groupBox_29 = QtWidgets.QGroupBox(self.tab_rep_pedales)
		self.groupBox_29.setGeometry(QtCore.QRect(10, 130, 471, 191))
		self.groupBox_29.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_29.setObjectName("groupBox_29")
		self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_29)
		self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 441, 161))
		self.layoutWidget4.setObjectName("layoutWidget4")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget4)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.frame_17 = QtWidgets.QFrame(self.layoutWidget4)
		self.frame_17.setStyleSheet("#frame_17:hover{    \n"
"color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_17.setObjectName("frame_17")
		self.layoutWidget5 = QtWidgets.QWidget(self.frame_17)
		self.layoutWidget5.setGeometry(QtCore.QRect(10, 10, 421, 27))
		self.layoutWidget5.setObjectName("layoutWidget5")
		self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget5)
		self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_18.setObjectName("horizontalLayout_18")
		self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget5)
		self.lineEdit_8.setMinimumSize(QtCore.QSize(16, 23))
		self.lineEdit_8.setStyleSheet("QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(171, 173, 179);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"\n"
"")
		self.lineEdit_8.setObjectName("lineEdit_8")
		self.horizontalLayout_18.addWidget(self.lineEdit_8)
		self.comboBox_11 = QtWidgets.QComboBox(self.layoutWidget5)
		self.comboBox_11.setMinimumSize(QtCore.QSize(331, 25))
		self.comboBox_11.setMaximumSize(QtCore.QSize(73, 16777215))
		self.comboBox_11.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    text-align: right;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_11.setObjectName("comboBox_11")
		self.comboBox_11.addItem("")
		self.horizontalLayout_18.addWidget(self.comboBox_11)
		self.verticalLayout.addWidget(self.frame_17)
		self.frame_19 = QtWidgets.QFrame(self.layoutWidget4)
		self.frame_19.setStyleSheet("border: 1px solid rgb(217, 217, 217);\n"
"background-color: rgb(238, 238, 238);")
		self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_19.setObjectName("frame_19")
		self.layoutWidget_8 = QtWidgets.QWidget(self.frame_19)
		self.layoutWidget_8.setGeometry(QtCore.QRect(10, 10, 421, 27))
		self.layoutWidget_8.setObjectName("layoutWidget_8")
		self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
		self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_21.setObjectName("horizontalLayout_21")
		self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_8)
		self.lineEdit_20.setMinimumSize(QtCore.QSize(16, 23))
		self.lineEdit_20.setStyleSheet("QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(171, 173, 179);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"\n"
"")
		self.lineEdit_20.setObjectName("lineEdit_20")
		self.horizontalLayout_21.addWidget(self.lineEdit_20)
		self.comboBox_17 = QtWidgets.QComboBox(self.layoutWidget_8)
		self.comboBox_17.setMinimumSize(QtCore.QSize(331, 25))
		self.comboBox_17.setMaximumSize(QtCore.QSize(73, 16777215))
		self.comboBox_17.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    text-align: right;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_17.setObjectName("comboBox_17")
		self.comboBox_17.addItem("")
		self.horizontalLayout_21.addWidget(self.comboBox_17)
		self.verticalLayout.addWidget(self.frame_19)
		self.frame_20 = QtWidgets.QFrame(self.layoutWidget4)
		self.frame_20.setStyleSheet("#frame_20:hover{    \n"
"color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_20.setObjectName("frame_20")
		self.layoutWidget_10 = QtWidgets.QWidget(self.frame_20)
		self.layoutWidget_10.setGeometry(QtCore.QRect(10, 10, 421, 27))
		self.layoutWidget_10.setObjectName("layoutWidget_10")
		self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
		self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_23.setObjectName("horizontalLayout_23")
		self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_10)
		self.lineEdit_22.setMinimumSize(QtCore.QSize(16, 23))
		self.lineEdit_22.setStyleSheet("QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(171, 173, 179);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"\n"
"")
		self.lineEdit_22.setObjectName("lineEdit_22")
		self.horizontalLayout_23.addWidget(self.lineEdit_22)
		self.comboBox_19 = QtWidgets.QComboBox(self.layoutWidget_10)
		self.comboBox_19.setMinimumSize(QtCore.QSize(331, 25))
		self.comboBox_19.setMaximumSize(QtCore.QSize(73, 16777215))
		self.comboBox_19.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    text-align: right;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_19.setObjectName("comboBox_19")
		self.comboBox_19.addItem("")
		self.horizontalLayout_23.addWidget(self.comboBox_19)
		self.verticalLayout.addWidget(self.frame_20)
		self.tabWidget_3.addTab(self.tab_rep_pedales, "")
		self.tab_rep_desc = QtWidgets.QWidget()
		self.tab_rep_desc.setObjectName("tab_rep_desc")
		self.groupBox_30 = QtWidgets.QGroupBox(self.tab_rep_desc)
		self.groupBox_30.setGeometry(QtCore.QRect(10, 10, 471, 121))
		self.groupBox_30.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_30.setObjectName("groupBox_30")
		self.tableWidget_5 = QtWidgets.QTableWidget(self.groupBox_30)
		self.tableWidget_5.setGeometry(QtCore.QRect(10, 30, 441, 71))
		self.tableWidget_5.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494, y2:0, stop:0 rgba(117, 160, 229, 255), stop:1 rgba(233, 238, 248, 255));\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    border:none;\n"
"    border-left: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    color: black;\n"
"}\n"
"")
		self.tableWidget_5.setObjectName("tableWidget_5")
		self.tableWidget_5.setColumnCount(3)
		self.tableWidget_5.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_5.setHorizontalHeaderItem(2, item)
		self.tabWidget_3.addTab(self.tab_rep_desc, "")
		self.tab_rep_info = QtWidgets.QWidget()
		self.tab_rep_info.setObjectName("tab_rep_info")
		self.groupBox_31 = QtWidgets.QGroupBox(self.tab_rep_info)
		self.groupBox_31.setGeometry(QtCore.QRect(10, 10, 471, 111))
		self.groupBox_31.setObjectName("groupBox_31")
		self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_31)
		self.lineEdit_11.setGeometry(QtCore.QRect(20, 30, 301, 31))
		self.lineEdit_11.setStyleSheet("QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(171, 173, 179);\n"
"    border-radius: 3px;\n"
"}\n"
"")
		self.lineEdit_11.setObjectName("lineEdit_11")
		self.widget = QtWidgets.QWidget(self.groupBox_31)
		self.widget.setGeometry(QtCore.QRect(340, 20, 111, 80))
		self.widget.setStyleSheet("border:1px solid rgb(0, 0, 0)")
		self.widget.setObjectName("widget")
		self.tabWidget_3.addTab(self.tab_rep_info, "")
		self.stackedWidget.addWidget(self.page_4)
		self.page_5 = QtWidgets.QWidget()
		self.page_5.setObjectName("page_5")
		self.frame_9 = QtWidgets.QFrame(self.page_5)
		self.frame_9.setGeometry(QtCore.QRect(0, 210, 21, 41))
		self.frame_9.setStyleSheet("background-color: qconicalgradient(cx:0.663, cy:0.511, angle:90.9, stop:0.351648 rgba(255, 255, 255, 0), stop:0.664773 rgba(255, 255, 255, 0), stop:0.670455 rgba(240, 240, 240, 255), stop:0.823864 rgba(240, 240, 240, 255), stop:0.829545 rgba(255, 255, 255, 0));")
		self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_9.setObjectName("frame_9")
		self.frame_15 = QtWidgets.QFrame(self.page_5)
		self.frame_15.setGeometry(QtCore.QRect(20, 0, 491, 401))
		self.frame_15.setStyleSheet("background-color: rgb(245, 245, 245);")
		self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_15.setObjectName("frame_15")
		self.groupBox_32 = QtWidgets.QGroupBox(self.frame_15)
		self.groupBox_32.setGeometry(QtCore.QRect(10, 10, 471, 211))
		self.groupBox_32.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_32.setObjectName("groupBox_32")
		self.tableWidget_6 = QtWidgets.QTableWidget(self.groupBox_32)
		self.tableWidget_6.setGeometry(QtCore.QRect(10, 20, 451, 141))
		self.tableWidget_6.setStyleSheet("QHeaderView::section {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.494, y2:0, stop:0 rgba(117, 160, 229, 255), stop:1 rgba(233, 238, 248, 255));\n"
"    color: black;\n"
"    padding-left: 5px;\n"
"    border:none;\n"
"    border-left: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QTableWidget{\n"
"    color: black;\n"
"}\n"
"\n"
"")
		self.tableWidget_6.setObjectName("tableWidget_6")
		self.tableWidget_6.setColumnCount(5)
		self.tableWidget_6.setRowCount(0)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setHorizontalHeaderItem(0, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setHorizontalHeaderItem(1, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setHorizontalHeaderItem(2, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setHorizontalHeaderItem(3, item)
		item = QtWidgets.QTableWidgetItem()
		self.tableWidget_6.setHorizontalHeaderItem(4, item)
		self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_32)
		self.layoutWidget6.setGeometry(QtCore.QRect(180, 170, 271, 31))
		self.layoutWidget6.setObjectName("layoutWidget6")
		self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget6)
		self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_20.setObjectName("horizontalLayout_20")
		self.pushButton_25 = QtWidgets.QPushButton(self.layoutWidget6)
		self.pushButton_25.setMinimumSize(QtCore.QSize(0, 27))
		self.pushButton_25.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
		self.pushButton_25.setObjectName("pushButton_25")
		self.horizontalLayout_20.addWidget(self.pushButton_25)
		self.pushButton_24 = QtWidgets.QPushButton(self.layoutWidget6)
		self.pushButton_24.setMinimumSize(QtCore.QSize(0, 27))
		self.pushButton_24.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
		self.pushButton_24.setObjectName("pushButton_24")
		self.horizontalLayout_20.addWidget(self.pushButton_24)
		self.pushButton_23 = QtWidgets.QPushButton(self.layoutWidget6)
		self.pushButton_23.setMinimumSize(QtCore.QSize(0, 27))
		self.pushButton_23.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
		self.pushButton_23.setObjectName("pushButton_23")
		self.horizontalLayout_20.addWidget(self.pushButton_23)
		self.groupBox_33 = QtWidgets.QGroupBox(self.frame_15)
		self.groupBox_33.setGeometry(QtCore.QRect(10, 230, 471, 80))
		self.groupBox_33.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_33.setObjectName("groupBox_33")
		self.comboBox_14 = QtWidgets.QComboBox(self.groupBox_33)
		self.comboBox_14.setGeometry(QtCore.QRect(20, 30, 91, 22))
		self.comboBox_14.setStyleSheet("QComboBox{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(172, 172, 172);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494, y1:1, x2:0.5, y2:0, stop:0 rgba(230, 230, 230, 255), stop:1 rgba(239, 239, 239, 255));\n"
"    text-align: right;\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px solid rgb(86, 157, 229);\n"
"    background-color: qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.511, y2:0, stop:0 rgba(220, 236, 252, 255), stop:1 rgba(234, 243, 252, 255));\n"
"}")
		self.comboBox_14.setObjectName("comboBox_14")
		self.comboBox_14.addItem("")
		self.stackedWidget.addWidget(self.page_5)
		self.page_6 = QtWidgets.QWidget()
		self.page_6.setObjectName("page_6")
		self.frame_10 = QtWidgets.QFrame(self.page_6)
		self.frame_10.setGeometry(QtCore.QRect(0, 260, 21, 41))
		self.frame_10.setStyleSheet("background-color: qconicalgradient(cx:0.663, cy:0.511, angle:90.9, stop:0.351648 rgba(255, 255, 255, 0), stop:0.664773 rgba(255, 255, 255, 0), stop:0.670455 rgba(240, 240, 240, 255), stop:0.823864 rgba(240, 240, 240, 255), stop:0.829545 rgba(255, 255, 255, 0));")
		self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_10.setObjectName("frame_10")
		self.frame_16 = QtWidgets.QFrame(self.page_6)
		self.frame_16.setGeometry(QtCore.QRect(20, 0, 491, 401))
		self.frame_16.setStyleSheet("background-color: rgb(245, 245, 245);")
		self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_16.setObjectName("frame_16")
		self.groupBox_34 = QtWidgets.QGroupBox(self.frame_16)
		self.groupBox_34.setGeometry(QtCore.QRect(10, 0, 471, 251))
		self.groupBox_34.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_34.setObjectName("groupBox_34")
		self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_34)
		self.pushButton_26.setGeometry(QtCore.QRect(360, 210, 91, 29))
		self.pushButton_26.setMinimumSize(QtCore.QSize(0, 29))
		self.pushButton_26.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.494318, y1:1, x2:0.5, y2:0, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.505682, y1:1, x2:0.505227, y2:0, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    border: none;\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: qlineargradient(spread:pad, x1:0.511, y1:0, x2:0.568, y2:1, stop:0 rgba(116, 159, 229, 255), stop:1 rgba(228, 235, 247, 255));\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.488, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: rgb(136, 136, 136);\n"
"    border: 1px solid rgb(167, 167, 167);\n"
"    \n"
"    background-color: rgb(238, 238, 238);\n"
"}\n"
"")
		self.pushButton_26.setObjectName("pushButton_26")
		self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_34)
		self.layoutWidget_5.setGeometry(QtCore.QRect(20, 30, 441, 171))
		self.layoutWidget_5.setObjectName("layoutWidget_5")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
		self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_5.setSpacing(1)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_12.setObjectName("horizontalLayout_12")
		self.label_25 = QtWidgets.QLabel(self.layoutWidget_5)
		self.label_25.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_25.setObjectName("label_25")
		self.horizontalLayout_12.addWidget(self.label_25)
		spacerItem = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_12.addItem(spacerItem)
		self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget_5)
		self.lineEdit_12.setMinimumSize(QtCore.QSize(0, 24))
		self.lineEdit_12.setStyleSheet("border: 1px solid rgb(208, 208, 191);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
		self.lineEdit_12.setObjectName("lineEdit_12")
		self.horizontalLayout_12.addWidget(self.lineEdit_12)
		self.verticalLayout_5.addLayout(self.horizontalLayout_12)
		self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_13.setObjectName("horizontalLayout_13")
		self.label_26 = QtWidgets.QLabel(self.layoutWidget_5)
		self.label_26.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_26.setObjectName("label_26")
		self.horizontalLayout_13.addWidget(self.label_26)
		spacerItem1 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_13.addItem(spacerItem1)
		self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget_5)
		self.lineEdit_13.setMinimumSize(QtCore.QSize(0, 24))
		self.lineEdit_13.setStyleSheet("border: 1px solid rgb(208, 208, 191);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
		self.lineEdit_13.setObjectName("lineEdit_13")
		self.horizontalLayout_13.addWidget(self.lineEdit_13)
		self.verticalLayout_5.addLayout(self.horizontalLayout_13)
		self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_14.setObjectName("horizontalLayout_14")
		self.label_27 = QtWidgets.QLabel(self.layoutWidget_5)
		self.label_27.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_27.setObjectName("label_27")
		self.horizontalLayout_14.addWidget(self.label_27)
		spacerItem2 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_14.addItem(spacerItem2)
		self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget_5)
		self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 24))
		self.lineEdit_14.setStyleSheet("border: 1px solid rgb(208, 208, 191);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
		self.lineEdit_14.setObjectName("lineEdit_14")
		self.horizontalLayout_14.addWidget(self.lineEdit_14)
		self.verticalLayout_5.addLayout(self.horizontalLayout_14)
		self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_15.setObjectName("horizontalLayout_15")
		self.label_28 = QtWidgets.QLabel(self.layoutWidget_5)
		self.label_28.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_28.setObjectName("label_28")
		self.horizontalLayout_15.addWidget(self.label_28)
		spacerItem3 = QtWidgets.QSpacerItem(56, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_15.addItem(spacerItem3)
		self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget_5)
		self.lineEdit_15.setMinimumSize(QtCore.QSize(0, 24))
		self.lineEdit_15.setStyleSheet("border: 1px solid rgb(208, 208, 191);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
		self.lineEdit_15.setObjectName("lineEdit_15")
		self.horizontalLayout_15.addWidget(self.lineEdit_15)
		self.verticalLayout_5.addLayout(self.horizontalLayout_15)
		self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_16.setObjectName("horizontalLayout_16")
		self.label_29 = QtWidgets.QLabel(self.layoutWidget_5)
		self.label_29.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_29.setObjectName("label_29")
		self.horizontalLayout_16.addWidget(self.label_29)
		spacerItem4 = QtWidgets.QSpacerItem(26, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_16.addItem(spacerItem4)
		self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_5)
		self.lineEdit_16.setMinimumSize(QtCore.QSize(0, 24))
		self.lineEdit_16.setStyleSheet("border: 1px solid rgb(208, 208, 191);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
		self.lineEdit_16.setObjectName("lineEdit_16")
		self.horizontalLayout_16.addWidget(self.lineEdit_16)
		self.verticalLayout_5.addLayout(self.horizontalLayout_16)
		self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_17.setObjectName("horizontalLayout_17")
		self.label_30 = QtWidgets.QLabel(self.layoutWidget_5)
		self.label_30.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_30.setObjectName("label_30")
		self.horizontalLayout_17.addWidget(self.label_30)
		spacerItem5 = QtWidgets.QSpacerItem(72, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
		self.horizontalLayout_17.addItem(spacerItem5)
		self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_5)
		self.lineEdit_17.setMinimumSize(QtCore.QSize(0, 24))
		self.lineEdit_17.setStyleSheet("border: 1px solid rgb(208, 208, 191);\n"
"border-radius: 3px;\n"
"color: rgb(0, 0, 0);")
		self.lineEdit_17.setObjectName("lineEdit_17")
		self.horizontalLayout_17.addWidget(self.lineEdit_17)
		self.verticalLayout_5.addLayout(self.horizontalLayout_17)
		self.groupBox_35 = QtWidgets.QGroupBox(self.frame_16)
		self.groupBox_35.setGeometry(QtCore.QRect(10, 250, 471, 141))
		self.groupBox_35.setStyleSheet("color: rgb(0, 0, 255);")
		self.groupBox_35.setObjectName("groupBox_35")
		self.label_31 = QtWidgets.QLabel(self.groupBox_35)
		self.label_31.setGeometry(QtCore.QRect(10, 20, 47, 13))
		self.label_31.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_31.setObjectName("label_31")
		self.label_32 = QtWidgets.QLabel(self.groupBox_35)
		self.label_32.setGeometry(QtCore.QRect(70, 20, 47, 13))
		self.label_32.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_32.setObjectName("label_32")
		self.label_33 = QtWidgets.QLabel(self.groupBox_35)
		self.label_33.setGeometry(QtCore.QRect(110, 20, 47, 16))
		self.label_33.setStyleSheet("Qlabel{\n"
"    color: rgb(136, 221, 245);\n"
"}\n"
"QLabel:hover{\n"
"    color: rgb(255, 0, 0);\n"
"}")
		self.label_33.setObjectName("label_33")
		self.label_34 = QtWidgets.QLabel(self.groupBox_35)
		self.label_34.setGeometry(QtCore.QRect(10, 40, 451, 21))
		self.label_34.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_34.setTextFormat(QtCore.Qt.PlainText)
		self.label_34.setWordWrap(True)
		self.label_34.setObjectName("label_34")
		self.label_35 = QtWidgets.QLabel(self.groupBox_35)
		self.label_35.setGeometry(QtCore.QRect(20, 60, 421, 61))
		self.label_35.setStyleSheet("color: rgb(0, 0, 0);")
		self.label_35.setTextFormat(QtCore.Qt.PlainText)
		self.label_35.setWordWrap(True)
		self.label_35.setObjectName("label_35")
		self.stackedWidget.addWidget(self.page_6)
		self.frame_4 = QtWidgets.QFrame(Dialog)
		self.frame_4.setGeometry(QtCore.QRect(0, 430, 631, 61))
		self.frame_4.setStyleSheet("background-color: rgb(89, 89, 89);")
		self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
		self.frame_4.setObjectName("frame_4")
		self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
		self.pushButton_7.setGeometry(QtCore.QRect(520, 10, 101, 31))
		self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.506, y1:0, x2:0.511455, y2:1, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(89, 89, 89, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.506, y1:0, x2:0.511455, y2:1, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(89, 89, 89, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-bottom: 2px solid rgb(202, 202, 202);\n"
"    border-top: 2px solid rgb(70, 70, 70);\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}")
		self.pushButton_7.setCheckable(False)
		self.pushButton_7.setChecked(False)
		self.pushButton_7.setObjectName("pushButton_7")
		self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
		self.pushButton_8.setGeometry(QtCore.QRect(410, 10, 101, 31))
		self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.506, y1:0, x2:0.511455, y2:1, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(89, 89, 89, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.506, y1:0, x2:0.511455, y2:1, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(89, 89, 89, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-bottom: 2px solid rgb(202, 202, 202);\n"
"    border-top: 2px solid rgb(70, 70, 70);\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}")
		self.pushButton_8.setCheckable(False)
		self.pushButton_8.setChecked(False)
		self.pushButton_8.setObjectName("pushButton_8")
		self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
		self.pushButton_9.setGeometry(QtCore.QRect(300, 10, 101, 31))
		self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top: 1px solid rgb(202, 202, 202);\n"
"    border-bottom: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.506, y1:0, x2:0.511455, y2:1, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(89, 89, 89, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.506, y1:0, x2:0.511455, y2:1, stop:0 rgba(202, 202, 202, 255), stop:1 rgba(89, 89, 89, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-bottom: 1px solid rgb(202, 202, 202);\n"
"    border-top: 1px solid rgb(70, 70, 70);\n"
"    border-left: 1px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 1px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: rgb(238, 238, 238);\n"
"    border-bottom: 2px solid rgb(202, 202, 202);\n"
"    border-top: 2px solid rgb(70, 70, 70);\n"
"    border-left: 2px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"    border-right: 2px solid qlineargradient(spread:pad, x1:0.494591, y1:0, x2:0.494318, y2:1, stop:0 rgba(70, 70, 70, 255), stop:1 rgba(202, 202, 202, 255));\n"
"}")
		self.pushButton_9.setCheckable(False)
		self.pushButton_9.setChecked(False)
		self.pushButton_9.setObjectName("pushButton_9")
		self.frame.raise_()
		self.frame_2.raise_()
		self.frame_4.raise_()
		self.frame_3.raise_()

		self.retranslateUi(Dialog)
		self.stackedWidget.setCurrentIndex(3)
		self.comboBox.setCurrentIndex(0)
		self.tabWidget_2.setCurrentIndex(0)
		self.tabWidget_3.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "                                                                                  Configuración"))
		self.pushButton.setText(_translate("Dialog", "General                 "))
		self.pushButton_2.setText(_translate("Dialog", "Visor                     "))
		self.pushButton_3.setText(_translate("Dialog", "Bandeja de Casos"))
		self.pushButton_4.setText(_translate("Dialog", "Reportador          "))
		self.pushButton_5.setText(_translate("Dialog", "Impresión DICOM"))
		self.pushButton_6.setText(_translate("Dialog", "Licencia               "))
		self.groupBox_3.setTitle(_translate("Dialog", "Modo de Visualización"))
		self.radioButton.setText(_translate("Dialog", "Automático"))
		self.radioButton_2.setText(_translate("Dialog", "Software"))
		self.groupBox_4.setTitle(_translate("Dialog", "Ubicación en Monitores"))
		item = self.tableWidget.horizontalHeaderItem(0)
		item.setText(_translate("Dialog", "Módulos"))
		item = self.tableWidget.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "Iniciar"))
		item = self.tableWidget.horizontalHeaderItem(2)
		item.setText(_translate("Dialog", "Monitor"))
		self.pushButton_10.setText(_translate("Dialog", "Identificar Monitores"))
		self.groupBox_2.setTitle(_translate("Dialog", "Idioma"))
		self.comboBox.setItemText(0, _translate("Dialog", "Español (España)"))
		self.lineEdit.setText(_translate("Dialog", "Station"))
		self.lineEdit_2.setText(_translate("Dialog", "10.0.40.181"))
		self.label.setText(_translate("Dialog", "Nombre de Entidad"))
		self.label_2.setText(_translate("Dialog", "IP"))
		self.pushButton_11.setText(_translate("Dialog", "Valores por defecto"))
		self.groupBox_7.setTitle(_translate("Dialog", "Puntos de anclaje"))
		self.label_11.setText(_translate("Dialog", "Color de relleno"))
		self.comboBox_7.setItemText(0, _translate("Dialog", "Red"))
		self.label_12.setText(_translate("Dialog", "Color seleccionado"))
		self.comboBox_8.setItemText(0, _translate("Dialog", "Blue"))
		self.label_13.setText(_translate("Dialog", "Radio"))
		self.groupBox_8.setTitle(_translate("Dialog", "Vista previa"))
		self.groupBox_6.setTitle(_translate("Dialog", "Mediciones"))
		self.label_3.setText(_translate("Dialog", "Color de borde"))
		self.comboBox_2.setItemText(0, _translate("Dialog", "#FF808080"))
		self.label_4.setText(_translate("Dialog", "Color de relleno"))
		self.comboBox_3.setItemText(0, _translate("Dialog", "Blue"))
		self.label_5.setText(_translate("Dialog", "Ancho de línea"))
		self.groupBox_20.setTitle(_translate("Dialog", "Dirección de la bandeja de entrada"))
		self.lineEdit_6.setText(_translate("Dialog", "C:\\"))
		self.pushButton_18.setText(_translate("Dialog", "Examinar"))
		self.groupBox_21.setTitle(_translate("Dialog", "Puerto"))
		self.groupBox_22.setTitle(_translate("Dialog", "Nodos"))
		item = self.tableWidget_4.horizontalHeaderItem(0)
		item.setText(_translate("Dialog", "Tipo"))
		item = self.tableWidget_4.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "Nombre del nodo"))
		item = self.tableWidget_4.horizontalHeaderItem(2)
		item.setText(_translate("Dialog", "Título EA"))
		item = self.tableWidget_4.horizontalHeaderItem(3)
		item.setText(_translate("Dialog", "IP"))
		item = self.tableWidget_4.horizontalHeaderItem(4)
		item.setText(_translate("Dialog", "Puerto"))
		self.pushButton_21.setText(_translate("Dialog", "Adicionar"))
		self.pushButton_20.setText(_translate("Dialog", "Modificar"))
		self.pushButton_19.setText(_translate("Dialog", "Eliminar"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_general_2), _translate("Dialog", "General"))
		self.label_16.setText(_translate("Dialog", "Operaciones concurrentes durante el envío:"))
		self.label_17.setText(_translate("Dialog", "Operaciones concurrentes durante la obtención:"))
		self.groupBox_23.setTitle(_translate("Dialog", "En caso de fallo"))
		self.radioButton_7.setText(_translate("Dialog", "Volver a intentar indefinidamente."))
		self.radioButton_8.setText(_translate("Dialog", "No volver a intentar"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_envio_obtencion_2), _translate("Dialog", "Envío/Obtención"))
		self.groupBox_24.setTitle(_translate("Dialog", "Esquema de trabajo"))
		self.radioButton_9.setText(_translate("Dialog", "Aislado"))
		self.radioButton_10.setText(_translate("Dialog", "Especialista con transcripción"))
		self.radioButton_11.setText(_translate("Dialog", "Especialista sin transcripción"))
		self.groupBox_25.setTitle(_translate("Dialog", "Conexión"))
		self.label_18.setText(_translate("Dialog", "URL:"))
		self.lineEdit_7.setText(_translate("Dialog", "http://10.56.9.220/Test/XAVIA.ReportService/Service.asmx"))
		self.groupBox_26.setTitle(_translate("Dialog", "Tamaño de letra"))
		self.groupBox_27.setTitle(_translate("Dialog", "Reproductor"))
		self.label_19.setText(_translate("Dialog", "Saltar"))
		self.label_20.setText(_translate("Dialog", "segundo(s) al mover hacia delante o atrás"))
		self.label_21.setText(_translate("Dialog", "Saltar"))
		self.label_22.setText(_translate("Dialog", "segundo(s) hacia atrás al pausar la reproducción"))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_rep_general), _translate("Dialog", "General"))
		self.groupBox_28.setTitle(_translate("Dialog", "Controladores"))
		self.label_23.setText(_translate("Dialog", "Controlador:"))
		self.label_24.setText(_translate("Dialog", "Puerto serie:"))
		self.comboBox_9.setItemText(0, _translate("Dialog", "AlasSerialPortsHAsod"))
		self.groupBox_29.setTitle(_translate("Dialog", "Pedal/Función"))
		self.lineEdit_8.setText(_translate("Dialog", "Pedal Button 1"))
		self.comboBox_11.setItemText(0, _translate("Dialog", "Retroceder"))
		self.lineEdit_20.setText(_translate("Dialog", "Pedal Button 2"))
		self.comboBox_17.setItemText(0, _translate("Dialog", "Reproducir/Pausar"))
		self.lineEdit_22.setText(_translate("Dialog", "Pedal Button 3"))
		self.comboBox_19.setItemText(0, _translate("Dialog", "Adelantar"))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_rep_pedales), _translate("Dialog", "Pedales"))
		self.groupBox_30.setTitle(_translate("Dialog", "Asociación entre el equipo y el campo \'Descripción del estudio\'"))
		item = self.tableWidget_5.horizontalHeaderItem(0)
		item.setText(_translate("Dialog", "Nombre del equipo"))
		item = self.tableWidget_5.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "Nombre del campo"))
		item = self.tableWidget_5.horizontalHeaderItem(2)
		item.setText(_translate("Dialog", "Identificador de la fuente"))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_rep_desc), _translate("Dialog", "Descripción del Estudio"))
		self.groupBox_31.setTitle(_translate("Dialog", "Encabezado"))
		self.lineEdit_11.setText(_translate("Dialog", "Encabezado"))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_rep_info), _translate("Dialog", "Información"))
		self.groupBox_32.setTitle(_translate("Dialog", "Impresoras"))
		item = self.tableWidget_6.horizontalHeaderItem(0)
		item.setText(_translate("Dialog", "Nombre de la impresora"))
		item = self.tableWidget_6.horizontalHeaderItem(1)
		item.setText(_translate("Dialog", "Título EA"))
		item = self.tableWidget_6.horizontalHeaderItem(2)
		item.setText(_translate("Dialog", "IP"))
		item = self.tableWidget_6.horizontalHeaderItem(3)
		item.setText(_translate("Dialog", "Puerto"))
		item = self.tableWidget_6.horizontalHeaderItem(4)
		item.setText(_translate("Dialog", "Modelo"))
		self.pushButton_25.setText(_translate("Dialog", "Adicionar"))
		self.pushButton_24.setText(_translate("Dialog", "Modificar"))
		self.pushButton_23.setText(_translate("Dialog", "Eliminar"))
		self.groupBox_33.setTitle(_translate("Dialog", "Tamaño de letra"))
		self.comboBox_14.setItemText(0, _translate("Dialog", "Mediana"))
		self.groupBox_34.setTitle(_translate("Dialog", "Información de registro"))
		self.pushButton_26.setText(_translate("Dialog", "Comprobar serial"))
		self.label_25.setText(_translate("Dialog", "Código de PC"))
		self.lineEdit_12.setText(_translate("Dialog", "97695"))
		self.label_26.setText(_translate("Dialog", "Creación"))
		self.lineEdit_13.setText(_translate("Dialog", "31/1/2022"))
		self.label_27.setText(_translate("Dialog", "Expiración"))
		self.lineEdit_14.setText(_translate("Dialog", "1/1/2024"))
		self.label_28.setText(_translate("Dialog", "Duración"))
		self.lineEdit_15.setText(_translate("Dialog", "700"))
		self.label_29.setText(_translate("Dialog", "Días Restantes"))
		self.lineEdit_16.setText(_translate("Dialog", "665"))
		self.label_30.setText(_translate("Dialog", "Serial"))
		self.lineEdit_17.setText(_translate("Dialog", "1ls7t04hu9ssDZdZrlUWZxfkHmi+J8EmLCdOR5ao6iLSVtqerxvwskoB62FRjkMI"))
		self.groupBox_35.setTitle(_translate("Dialog", "Información del sistema"))
		self.label_31.setText(_translate("Dialog", "Versión:"))
		self.label_32.setText(_translate("Dialog", "3.2"))
		self.label_33.setText(_translate("Dialog", "Detalles"))
		self.label_34.setText(_translate("Dialog", "Universidad de las Ciencias Informaticas. XAVIA PACSViewer. Todos los derechos reservados."))
		self.label_35.setText(_translate("Dialog", "Registro # 4048-12-2018. Registrado en Cuba en el CENDA a nombre de la UCI. Registro # 622-0090. Registrado en Cuba en el Registro de Sistemas Comercializables a nombre del Ministerio de las Comunicaciones.                                                                  Registro Sanitario 11811001. Registrado en Cuba en el CECMED."))
		self.pushButton_7.setText(_translate("Dialog", "Cancelar"))
		self.pushButton_8.setText(_translate("Dialog", "Aplicar"))
		self.pushButton_9.setText(_translate("Dialog", "Aceptar"))
import assets.resources
